import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { useAuth } from '../contexts/AuthContext'
import { parseFastApiError } from '../../api/errors'
import { twoFactorApi } from '../../api/twoFactor'
import type { TwoFactorEnableResponse } from '../../api/types'

const schema = z.object({
  code: z.string().trim().regex(/^\d{6}$/, 'Enter the 6-digit code from your authenticator app'),
})

type FormValues = z.infer<typeof schema>

export default function SetupMFAPage() {
  const navigate = useNavigate()
  const { refreshUser } = useAuth()
  const [setup, setSetup] = useState<TwoFactorEnableResponse | null>(null)
  const [alreadyEnabled, setAlreadyEnabled] = useState(false)
  const [isVerified, setIsVerified] = useState(false)
  const [backupCodes, setBackupCodes] = useState<string[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [isVerifying, setIsVerifying] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  const { register, handleSubmit, formState: { errors } } = useForm<FormValues>({
    resolver: zodResolver(schema),
    mode: 'onChange',
  })

  useEffect(() => {
    let mounted = true

    twoFactorApi.enable()
      .then((response) => {
        if (!mounted) return
        setSetup(response)
      })
      .catch((err) => {
        if (!mounted) return
        if (err?.response?.status === 409) {
          setAlreadyEnabled(true)
          return
        }
        setError(parseFastApiError(err))
      })
      .finally(() => {
        if (!mounted) return
        setIsLoading(false)
      })

    return () => {
      mounted = false
    }
  }, [])

  const handleCopy = async () => {
    if (!backupCodes.length) return
    await navigator.clipboard.writeText(backupCodes.join('\n'))
    setCopied(true)
    window.setTimeout(() => setCopied(false), 2000)
  }

  const handleGenerateBackupCodes = async () => {
    setError(null)
    setSuccess(null)
    setIsVerifying(true)

    try {
      const generated = await twoFactorApi.backupCodes()
      setBackupCodes(generated.backup_codes)
      await refreshUser()
      setSuccess('Backup codes generated. Save them now; they are shown only once.')
    } catch (err: any) {
      setError(parseFastApiError(err))
    } finally {
      setIsVerifying(false)
    }
  }

  const onVerify = async (values: FormValues) => {
    if (!setup) return
    setError(null)
    setSuccess(null)
    setIsVerifying(true)

    try {
      await twoFactorApi.verify({
        setup_token: setup.setup_token,
        code: values.code,
      })

      setIsVerified(true)
      await handleGenerateBackupCodes()
      await refreshUser()
      setSuccess('Two-factor authentication is enabled. Save these backup codes now; they are shown only once.')
    } catch (err: any) {
      setError(parseFastApiError(err))
    } finally {
      setIsVerifying(false)
    }
  }

  return (
    <div className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(15,23,42,0.25),_transparent_38%),linear-gradient(180deg,_#0f172a_0%,_#111827_44%,_#f8fafc_44%,_#f8fafc_100%)] px-4 py-10">
      <div className="mx-auto max-w-6xl">
        <div className="overflow-hidden rounded-[2rem] border border-white/10 bg-white shadow-[0_30px_120px_rgba(15,23,42,0.22)] lg:grid lg:grid-cols-[1.02fr_0.98fr]">
          <div className="bg-slate-950 p-8 text-white lg:p-10">
            <div className="space-y-4">
              <div className="inline-flex rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-medium uppercase tracking-[0.24em] text-white/70">
                Setup MFA
              </div>
              <h1 className="text-3xl font-semibold tracking-tight">Scan the QR code with your authenticator app</h1>
              <p className="max-w-xl text-sm leading-6 text-white/70">
                Use Google Authenticator, Authy, or 1Password. The QR code is generated by the server and the shared secret is never exposed directly.
              </p>
            </div>

            <div className="mt-8 grid gap-3 text-sm text-white/70 sm:grid-cols-3">
              <div className="rounded-2xl border border-white/10 bg-white/5 p-4">QR generated server-side</div>
              <div className="rounded-2xl border border-white/10 bg-white/5 p-4">TOTP compatible</div>
              <div className="rounded-2xl border border-white/10 bg-white/5 p-4">10 backup codes</div>
            </div>
          </div>

          <div className="p-8 lg:p-10">
            {isLoading ? (
              <div className="space-y-4">
                <div className="h-8 w-56 animate-pulse rounded bg-slate-200" />
                <div className="h-72 animate-pulse rounded-3xl bg-slate-100" />
              </div>
            ) : error && !setup && !alreadyEnabled ? (
              <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>
            ) : alreadyEnabled ? (
              <div className="space-y-6">
                <div className="space-y-2">
                  <h2 className="text-2xl font-semibold tracking-tight text-slate-950">Backup code management</h2>
                  <p className="text-sm text-slate-500">2FA is already active. Generate a fresh backup code set if needed.</p>
                </div>

                <button
                  type="button"
                  onClick={handleGenerateBackupCodes}
                  disabled={isVerifying}
                  className="rounded-2xl bg-slate-950 px-5 py-3 text-sm font-medium text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50"
                >
                  {isVerifying ? 'Generating...' : 'Generate backup codes'}
                </button>

                {success && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{success}</div>}

                {backupCodes.length > 0 && (
                  <div className="space-y-4 rounded-[1.75rem] border border-amber-200 bg-amber-50 p-5">
                    <div className="flex flex-wrap items-center justify-between gap-3">
                      <div>
                        <h3 className="text-sm font-semibold text-amber-950">Backup codes</h3>
                        <p className="text-xs text-amber-800">Store these codes securely. They will not be shown again.</p>
                      </div>
                      <button
                        type="button"
                        onClick={handleCopy}
                        className="rounded-xl bg-amber-950 px-4 py-2 text-xs font-medium text-white transition hover:bg-amber-900"
                      >
                        {copied ? 'Copied' : 'Copy all'}
                      </button>
                    </div>

                    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                      {backupCodes.map((code) => (
                        <div key={code} className="rounded-2xl border border-amber-200 bg-white px-4 py-3 font-mono text-sm tracking-[0.22em] text-amber-950">
                          {code}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ) : setup && !isVerified ? (
              <div className="space-y-6">
                <div className="space-y-2">
                  <h2 className="text-2xl font-semibold tracking-tight text-slate-950">Confirm your authenticator</h2>
                  <p className="text-sm text-slate-500">Enter the 6-digit code generated by your app to finish activation.</p>
                </div>

                <div className="rounded-[1.75rem] border border-slate-200 bg-slate-50 p-5">
                  <img
                    src={setup.qr_code_base64}
                    alt="MFA QR code"
                    className="mx-auto aspect-square w-full max-w-sm rounded-3xl border border-white bg-white p-4 shadow-sm"
                  />
                </div>

                <form onSubmit={handleSubmit(onVerify)} className="space-y-4">
                  <div className="space-y-2">
                    <label className="text-sm font-medium text-slate-700">Authenticator code</label>
                    <input
                      type="text"
                      inputMode="numeric"
                      autoComplete="one-time-code"
                      placeholder="123456"
                      className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm tracking-[0.35em] text-slate-950 outline-none transition focus:border-slate-900"
                      {...register('code')}
                    />
                    {errors.code && <p className="text-xs text-red-600">{errors.code.message}</p>}
                  </div>

                  <div className="flex flex-wrap gap-3">
                    <button
                      type="submit"
                      disabled={isVerifying}
                      className="rounded-2xl bg-slate-950 px-5 py-3 text-sm font-medium text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      {isVerifying ? 'Verifying...' : 'Enable 2FA'}
                    </button>
                    <button
                      type="button"
                      onClick={() => navigate('/settings')}
                      className="rounded-2xl border border-slate-200 px-5 py-3 text-sm font-medium text-slate-700 transition hover:border-slate-400"
                    >
                      Back to settings
                    </button>
                  </div>
                </form>

                {success && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{success}</div>}

                {backupCodes.length > 0 && (
                  <div className="space-y-4 rounded-[1.75rem] border border-amber-200 bg-amber-50 p-5">
                    <div className="flex flex-wrap items-center justify-between gap-3">
                      <div>
                        <h3 className="text-sm font-semibold text-amber-950">Backup codes</h3>
                        <p className="text-xs text-amber-800">Store these codes securely. They will not be shown again.</p>
                      </div>
                      <button
                        type="button"
                        onClick={handleCopy}
                        className="rounded-xl bg-amber-950 px-4 py-2 text-xs font-medium text-white transition hover:bg-amber-900"
                      >
                        {copied ? 'Copied' : 'Copy all'}
                      </button>
                    </div>

                    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                      {backupCodes.map((code) => (
                        <div key={code} className="rounded-2xl border border-amber-200 bg-white px-4 py-3 font-mono text-sm tracking-[0.22em] text-amber-950">
                          {code}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ) : backupCodes.length > 0 ? (
              <div className="space-y-4 rounded-[1.75rem] border border-amber-200 bg-amber-50 p-5">
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <div>
                    <h3 className="text-sm font-semibold text-amber-950">Backup codes</h3>
                    <p className="text-xs text-amber-800">Store these codes securely. They will not be shown again.</p>
                  </div>
                  <button
                    type="button"
                    onClick={handleCopy}
                    className="rounded-xl bg-amber-950 px-4 py-2 text-xs font-medium text-white transition hover:bg-amber-900"
                  >
                    {copied ? 'Copied' : 'Copy all'}
                  </button>
                </div>

                <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                  {backupCodes.map((code) => (
                    <div key={code} className="rounded-2xl border border-amber-200 bg-white px-4 py-3 font-mono text-sm tracking-[0.22em] text-amber-950">
                      {code}
                    </div>
                  ))}
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  )
}
