export type Page = 'dashboard' | 'understand' | 'documents' | 'risks' | 'evidence' | 'findings' | 'audit' | 'integrity' | 'regfeed' | 'dora' | 'euai' | 'escalation' | 'integrations' | 'settings' | 'assets';
export type Language = 'en' | 'es' | 'pt' | 'de' | 'fr';
export type Profile = 'foundational' | 'established' | 'advanced' | 'mature';
export type DateFormat = 'dmy' | 'mdy' | 'ymd';

export const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    understand: 'Understand My Situation',
    documents: 'Document Controls',
    risks: 'Manage Risks',
    evidence: 'Collect Evidence',
    findings: 'Manage Findings',
    audit: 'Prepare for Audit',
    integrity: 'Compliance Integrity',
    regfeed: 'Regulatory Feed',
    settings: 'Settings',
    escalation: 'Escalation Rules',
    integrations: 'Integrations',
    gapAnalysis: 'Gap Analysis',
    documentGenerator: 'Document Generator',
    riskMap: 'Risk Map',
    evidenceCenter: 'Evidence Center',
    capaTracker: 'CAPA Tracker',
    auditRoom: 'Audit Room',

    // Common
    searchPlaceholder: 'Search controls or evidence...',
    administrator: 'Administrator',
    chatPlaceholder: 'Type a message...',
    send: 'Send',

    // Header
    'header.searchPlaceholder': 'Search controls or evidence...',
    'header.plan': 'Plan',
    'header.viewProfile': 'View Profile',
    'header.settings': 'Settings',
    'header.signOut': 'Sign Out',

    // Sidebar
    'sidebar.orgProfile': 'Organization Profile',
    'sidebar.change': 'Change',
    'sidebar.byProcess': 'By Process',
    'sidebar.byModule': 'By Module',
    'sidebar.complianceJourney': 'Compliance Journey',
    'sidebar.intelligence': 'Intelligence',
    'sidebar.coreModules': 'Core Modules',
    'sidebar.regulatoryModules': 'Regulatory Modules',
    'sidebar.settings': 'Settings',
    'sidebar.availableInPlan': 'Available in {plan} Plan',

    // Menu Items
    'menu.dashboard': 'Dashboard',
    'menu.understand': 'Understand',
    'menu.documents': 'Documents',
    'menu.risks': 'Risks',
    'menu.evidence': 'Evidence',
    'menu.findings': 'Findings',
    'menu.audit': 'Audit',
    'menu.integrity': 'Integrity',
    'menu.regfeed': 'Regulatory Feed',
    'menu.gapAnalysis': 'Gap Analysis',
    'menu.documentGenerator': 'Document Generator',
    'menu.riskMap': 'Risk Map',
    'menu.evidenceCenter': 'Evidence Center',
    'menu.capaTracker': 'CAPA Tracker',
    'menu.auditRoom': 'Audit Room',
    'menu.preAuditAssessment': 'Pre-Audit Self-Assessment',
    'menu.dora': 'DORA',
    'menu.euai': 'EU AI Act',
    'menu.escalation': 'Escalation Rules',
    'menu.integrations': 'Integrations',
    'menu.settings': 'Settings',
    'menu.assets': 'Asset Inventory',

    // Dashboard
    profile: 'Profile',
    exportReport: 'Export Report',
    addFramework: 'Add Framework',
    overallCompliance: 'Overall Compliance Health',
    documentation: 'Documentation',
    implementation: 'Implementation',
    tested: 'Tested / Effective',
    'dashboard.documentation': 'Documentation',
    'dashboard.implementation': 'Implementation',
    'dashboard.tested': 'Tested / Effective',
    autoTracked: 'Auto-tracked',
    reviewNeeded: 'Review needed',
    humanRequired: 'Human required',
    fromLastMonth: 'from last month',
    docsPending: 'docs pending review',
    controlsUnverified: 'controls unverified',
    controlsUntested: 'controls untested',
    'settings.title': 'Settings',
    'settings.subtitle': 'Tune language, appearance, notifications, and automation for your workspace.',
    'settings.organizationProfile': 'Organization Profile',
    'settings.currentProfile': 'Current profile',
    'settings.profile.foundational': 'Foundational',
    'settings.profile.established': 'Established',
    'settings.profile.advanced': 'Advanced',
    'settings.profile.mature': 'Mature',
    'settings.profileDesc.foundational': 'Guided mode with more help and explanations',
    'settings.profileDesc.established': 'Balanced mode with process and module navigation',
    'settings.profileDesc.advanced': 'Module-first mode with less guidance',
    'settings.profileDesc.mature': 'High-autonomy mode for advanced teams',
    'settings.languageRegion': 'Language & Region',
    'settings.interfaceLanguage': 'Interface language',
    'settings.controlsUI': 'Controls the language used across the platform',
    'settings.dateFormat': 'Date format',
    'settings.dateFormatHelp': 'How dates are displayed in the UI',
    'settings.timezone': 'Timezone',
    'settings.timezoneHelp': 'Used for reminders and timestamps',
    'settings.appearance': 'Appearance',
    'settings.darkMode': 'Dark mode',
    'settings.darkModeHelp': 'Switch between light and dark theme',
    'settings.compactView': 'Compact view',
    'settings.compactViewHelp': 'Reduce spacing in tables and cards',
    'settings.sidebarLabels': 'Show sidebar labels',
    'settings.sidebarLabelsHelp': 'Display text labels in the navigation',
    'settings.notifications': 'Notifications',
    'settings.emailNotifications': 'Email notifications',
    'settings.emailNotificationsHelp': 'Receive compliance alerts by email',
    'settings.capaReminders': 'CAPA reminders',
    'settings.capaRemindersHelp': 'Remind the team about overdue corrective actions',
    'settings.regulatoryUpdates': 'Regulatory updates',
    'settings.regulatoryUpdatesHelp': 'Alert on new regulatory changes',
    'settings.auditDeadlines': 'Audit deadlines',
    'settings.auditDeadlinesHelp': 'Notify before key audit dates',
    'settings.automationScheduling': 'Automation & Scheduling',
    'settings.autoSave': 'Auto-save',
    'settings.autoSaveHelp': 'Save changes automatically when possible',
    'settings.autoRunAnalysis': 'Auto-run analysis',
    'settings.autoRunAnalysisHelp': 'Schedule periodic gap analysis runs',
    'settings.scheduleFrequency': 'Schedule frequency',
    'settings.scheduleFrequencyHelp': 'Choose how often automated checks run',
    'settings.userManagement': 'User management',
    'settings.activeUser': 'Active user',
    'settings.inviteTeamMember': 'Invite team member',
  },
  es: {
    // Navigation
    dashboard: 'Panel de Control',
    understand: 'Entender Mi Situación',
    documents: 'Controles de Documentos',
    risks: 'Gestionar Riesgos',
    evidence: 'Recopilar Evidencia',
    findings: 'Gestionar Hallazgos',
    audit: 'Preparar Auditoría',
    integrity: 'Integridad de Cumplimiento',
    regfeed: 'Noticias Regulatorias',
    settings: 'Configuración',
    escalation: 'Reglas de Escalación',
    integrations: 'Integraciones',
    gapAnalysis: 'Análisis de Brechas',
    documentGenerator: 'Generador de Documentos',
    riskMap: 'Mapa de Riesgos',
    evidenceCenter: 'Centro de Evidencias',
    capaTracker: 'Seguimiento de CAPA',
    auditRoom: 'Sala de Auditoría',

    // Common
    searchPlaceholder: 'Buscar controles o evidencia...',
    administrator: 'Administrador',
    chatPlaceholder: 'Escribe un mensaje...',
    send: 'Enviar',

    // Header
    'header.searchPlaceholder': 'Buscar controles o evidencia...',
    'header.plan': 'Plan',
    'header.viewProfile': 'Ver Perfil',
    'header.settings': 'Configuración',
    'header.signOut': 'Cerrar Sesión',

    // Sidebar
    'sidebar.orgProfile': 'Perfil de Organización',
    'sidebar.change': 'Cambiar',
    'sidebar.byProcess': 'Por Proceso',
    'sidebar.byModule': 'Por Módulo',
    'sidebar.complianceJourney': 'Viaje de Cumplimiento',
    'sidebar.intelligence': 'Inteligencia',
    'sidebar.coreModules': 'Módulos Principales',
    'sidebar.regulatoryModules': 'Módulos Regulatorios',
    'sidebar.settings': 'Configuración',
    'sidebar.availableInPlan': 'Disponible en Plan {plan}',

    // Menu Items
    'menu.dashboard': 'Panel de Control',
    'menu.understand': 'Entender',
    'menu.documents': 'Documentos',
    'menu.risks': 'Riesgos',
    'menu.evidence': 'Evidencia',
    'menu.findings': 'Hallazgos',
    'menu.audit': 'Auditoría',
    'menu.integrity': 'Integridad',
    'menu.regfeed': 'Noticias Regulatorias',
    'menu.gapAnalysis': 'Análisis de Brechas',
    'menu.documentGenerator': 'Generador de Documentos',
    'menu.riskMap': 'Mapa de Riesgos',
    'menu.evidenceCenter': 'Centro de Evidencias',
    'menu.capaTracker': 'Seguimiento CAPA',
    'menu.auditRoom': 'Sala de Auditoría',
    'menu.preAuditAssessment': 'Autoevaluación Pre-Auditoría',
    'menu.dora': 'DORA',
    'menu.euai': 'Ley IA UE',
    'menu.escalation': 'Reglas de Escalación',
    'menu.integrations': 'Integraciones',
    'menu.settings': 'Configuración',
    'menu.assets': 'Inventario de Activos',

    // Dashboard
    profile: 'Perfil',
    exportReport: 'Exportar Reporte',
    addFramework: 'Agregar Framework',
    overallCompliance: 'Estado General de Cumplimiento',
    documentation: 'Documentación',
    implementation: 'Implementación',
    tested: 'Probado / Efectivo',
    'dashboard.documentation': 'Documentación',
    'dashboard.implementation': 'Implementación',
    'dashboard.tested': 'Probado / Efectivo',
    autoTracked: 'Auto-rastreado',
    reviewNeeded: 'Revisión necesaria',
    humanRequired: 'Humano requerido',
    fromLastMonth: 'desde el mes pasado',
    docsPending: 'docs pendientes de revisión',
    controlsUnverified: 'controles sin verificar',
    controlsUntested: 'controles sin probar',
    'settings.title': 'Configuración',
    'settings.subtitle': 'Ajusta idioma, apariencia, notificaciones y automatización del espacio.',
    'settings.organizationProfile': 'Perfil de Organización',
    'settings.currentProfile': 'Perfil actual',
    'settings.profile.foundational': 'Fundacional',
    'settings.profile.established': 'Establecido',
    'settings.profile.advanced': 'Avanzado',
    'settings.profile.mature': 'Maduro',
    'settings.profileDesc.foundational': 'Modo guiado con más ayuda y explicaciones',
    'settings.profileDesc.established': 'Modo equilibrado con navegación por proceso y módulos',
    'settings.profileDesc.advanced': 'Modo centrado en módulos con menos guía',
    'settings.profileDesc.mature': 'Modo de alta autonomía para equipos avanzados',
    'settings.languageRegion': 'Idioma y Región',
    'settings.interfaceLanguage': 'Idioma de la interfaz',
    'settings.controlsUI': 'Controla el idioma de toda la plataforma',
    'settings.dateFormat': 'Formato de fecha',
    'settings.dateFormatHelp': 'Cómo se muestran las fechas en la interfaz',
    'settings.timezone': 'Zona horaria',
    'settings.timezoneHelp': 'Usada para recordatorios y marcas de tiempo',
    'settings.appearance': 'Apariencia',
    'settings.darkMode': 'Modo oscuro',
    'settings.darkModeHelp': 'Alterna entre tema claro y oscuro',
    'settings.compactView': 'Vista compacta',
    'settings.compactViewHelp': 'Reduce el espacio en tablas y tarjetas',
    'settings.sidebarLabels': 'Mostrar etiquetas del menú',
    'settings.sidebarLabelsHelp': 'Muestra texto en la navegación lateral',
    'settings.notifications': 'Notificaciones',
    'settings.emailNotifications': 'Notificaciones por correo',
    'settings.emailNotificationsHelp': 'Recibe alertas de cumplimiento por correo',
    'settings.capaReminders': 'Recordatorios CAPA',
    'settings.capaRemindersHelp': 'Recuerda acciones correctivas vencidas',
    'settings.regulatoryUpdates': 'Actualizaciones regulatorias',
    'settings.regulatoryUpdatesHelp': 'Avísame cuando haya cambios regulatorios',
    'settings.auditDeadlines': 'Fechas de auditoría',
    'settings.auditDeadlinesHelp': 'Notifica antes de fechas clave',
    'settings.automationScheduling': 'Automatización y programación',
    'settings.autoSave': 'Guardado automático',
    'settings.autoSaveHelp': 'Guarda cambios automáticamente cuando sea posible',
    'settings.autoRunAnalysis': 'Ejecutar análisis automático',
    'settings.autoRunAnalysisHelp': 'Programa análisis de brechas periódicos',
    'settings.scheduleFrequency': 'Frecuencia de ejecución',
    'settings.scheduleFrequencyHelp': 'Elige cada cuánto se ejecutan las revisiones',
    'settings.userManagement': 'Gestión de usuarios',
    'settings.activeUser': 'Usuario activo',
    'settings.inviteTeamMember': 'Invitar miembro del equipo',
  },
  pt: {
    dashboard: 'Painel',
    understand: 'Entender Minha Situação',
    documents: 'Controles de Documentos',
    risks: 'Gerenciar Riscos',
    evidence: 'Coletar Evidências',
    findings: 'Gerenciar Achados',
    audit: 'Preparar Auditoria',
    integrity: 'Integridade de Conformidade',
    regfeed: 'Feed Regulatório',
    settings: 'Configurações',
    escalation: 'Regras de Escalação',
    integrations: 'Integrações',
    gapAnalysis: 'Análise de Lacunas',
    documentGenerator: 'Gerador de Documentos',
    riskMap: 'Mapa de Riscos',
    evidenceCenter: 'Centro de Evidências',
    capaTracker: 'Rastreador de CAPA',
    auditRoom: 'Sala de Auditoria',
    'menu.preAuditAssessment': 'Autoavaliação Pré-Auditoria',
    searchPlaceholder: 'Pesquisar controles ou evidências...',
    administrator: 'Administrador',
    chatPlaceholder: 'Digite uma mensagem...',
    send: 'Enviar',

    // Header
    'header.searchPlaceholder': 'Pesquisar controles ou evidências...',
    'header.plan': 'Plano',
    'header.viewProfile': 'Ver Perfil',
    'header.settings': 'Configurações',
    'header.signOut': 'Sair',

    // Sidebar
    'sidebar.orgProfile': 'Perfil da Organização',
    'sidebar.change': 'Mudar',
    'sidebar.byProcess': 'Por Processo',
    'sidebar.byModule': 'Por Módulo',
    'sidebar.complianceJourney': 'Jornada de Conformidade',
    'sidebar.intelligence': 'Inteligência',
    'sidebar.coreModules': 'Módulos Principais',
    'sidebar.regulatoryModules': 'Módulos Regulatórios',
    'sidebar.settings': 'Configurações',
    'sidebar.availableInPlan': 'Disponível no Plano {plan}',

    // Menu Items
    'menu.dashboard': 'Painel',
    'menu.understand': 'Entender',
    'menu.documents': 'Documentos',
    'menu.risks': 'Riscos',
    'menu.evidence': 'Evidências',
    'menu.findings': 'Achados',
    'menu.audit': 'Auditoria',
    'menu.integrity': 'Integridade',
    'menu.regfeed': 'Feed Regulatório',
    'menu.gapAnalysis': 'Análise de Lacunas',
    'menu.documentGenerator': 'Gerador de Documentos',
    'menu.riskMap': 'Mapa de Riscos',
    'menu.evidenceCenter': 'Centro de Evidências',
    'menu.capaTracker': 'Rastreador CAPA',
    'menu.auditRoom': 'Sala de Auditoria',
    'menu.dora': 'DORA',
    'menu.euai': 'Lei IA UE',
    'menu.escalation': 'Regras de Escalação',
    'menu.integrations': 'Integrações',
    'menu.settings': 'Configurações',
    'menu.assets': 'Inventário de Ativos',

    profile: 'Perfil',
    exportReport: 'Exportar Relatório',
    addFramework: 'Adicionar Framework',
    overallCompliance: 'Saúde Geral de Conformidade',
    documentation: 'Documentação',
    implementation: 'Implementação',
    tested: 'Testado / Efetivo',
    'dashboard.documentation': 'Documentação',
    'dashboard.implementation': 'Implementação',
    'dashboard.tested': 'Testado / Efetivo',
    autoTracked: 'Auto-rastreado',
    reviewNeeded: 'Revisão necessária',
    humanRequired: 'Humano necessário',
    fromLastMonth: 'do mês passado',
    docsPending: 'docs pendentes de revisão',
    controlsUnverified: 'controles não verificados',
    controlsUntested: 'controles não testados',
    'settings.title': 'Configurações',
    'settings.subtitle': 'Ajuste idioma, aparência, notificações e automação do seu espaço.',
    'settings.organizationProfile': 'Perfil da Organização',
    'settings.currentProfile': 'Perfil atual',
    'settings.profile.foundational': 'Fundacional',
    'settings.profile.established': 'Estabelecido',
    'settings.profile.advanced': 'Avançado',
    'settings.profile.mature': 'Maduro',
    'settings.profileDesc.foundational': 'Modo guiado com mais ajuda e explicações',
    'settings.profileDesc.established': 'Modo equilibrado com navegação por processo e módulos',
    'settings.profileDesc.advanced': 'Modo focado em módulos com menos orientação',
    'settings.profileDesc.mature': 'Modo de alta autonomia para equipes avançadas',
    'settings.languageRegion': 'Idioma e Região',
    'settings.interfaceLanguage': 'Idioma da interface',
    'settings.controlsUI': 'Controla o idioma de toda a plataforma',
    'settings.dateFormat': 'Formato de data',
    'settings.dateFormatHelp': 'Como as datas são exibidas na interface',
    'settings.timezone': 'Fuso horário',
    'settings.timezoneHelp': 'Usado para lembretes e horários',
    'settings.appearance': 'Aparência',
    'settings.darkMode': 'Modo escuro',
    'settings.darkModeHelp': 'Alterna entre tema claro e escuro',
    'settings.compactView': 'Visualização compacta',
    'settings.compactViewHelp': 'Reduz o espaço em tabelas e cartões',
    'settings.sidebarLabels': 'Mostrar rótulos da barra lateral',
    'settings.sidebarLabelsHelp': 'Exibe texto na navegação lateral',
    'settings.notifications': 'Notificações',
    'settings.emailNotifications': 'Notificações por e-mail',
    'settings.emailNotificationsHelp': 'Receba alertas de conformidade por e-mail',
    'settings.capaReminders': 'Lembretes CAPA',
    'settings.capaRemindersHelp': 'Lembra a equipe sobre ações corretivas vencidas',
    'settings.regulatoryUpdates': 'Atualizações regulatórias',
    'settings.regulatoryUpdatesHelp': 'Alertar sobre novas mudanças regulatórias',
    'settings.auditDeadlines': 'Prazos de auditoria',
    'settings.auditDeadlinesHelp': 'Notificar antes das datas-chave de auditoria',
    'settings.automationScheduling': 'Automação e Agendamento',
    'settings.autoSave': 'Salvamento automático',
    'settings.autoSaveHelp': 'Salva alterações automaticamente quando possível',
    'settings.autoRunAnalysis': 'Executar análise automática',
    'settings.autoRunAnalysisHelp': 'Agende análises periódicas de lacunas',
    'settings.scheduleFrequency': 'Frequência de execução',
    'settings.scheduleFrequencyHelp': 'Escolha com que frequência as verificações rodam',
    'settings.userManagement': 'Gestão de usuários',
    'settings.activeUser': 'Usuário ativo',
    'settings.inviteTeamMember': 'Convidar membro da equipe',
  },
  de: {
    dashboard: 'Dashboard',
    understand: 'Meine Situation Verstehen',
    documents: 'Dokumentenkontrollen',
    risks: 'Risiken Verwalten',
    evidence: 'Beweise Sammeln',
    findings: 'Befunde Verwalten',
    audit: 'Audit Vorbereiten',
    integrity: 'Compliance-Integrität',
    regfeed: 'Regulatorischer Feed',
    settings: 'Einstellungen',
    escalation: 'Eskalationsregeln',
    integrations: 'Integrationen',
    gapAnalysis: 'Lückenanalyse',
    documentGenerator: 'Dokumentengenerator',
    riskMap: 'Risikokarte',
    evidenceCenter: 'Beweiszentrum',
    capaTracker: 'CAPA-Tracker',
    auditRoom: 'Auditraum',
    searchPlaceholder: 'Kontrollen oder Beweise suchen...',
    administrator: 'Administrator',
    chatPlaceholder: 'Nachricht eingeben...',
    send: 'Senden',

    // Header
    'header.searchPlaceholder': 'Kontrollen oder Beweise suchen...',
    'header.plan': 'Plan',
    'header.viewProfile': 'Profil Anzeigen',
    'header.settings': 'Einstellungen',
    'header.signOut': 'Abmelden',

    // Sidebar
    'sidebar.orgProfile': 'Organisationsprofil',
    'sidebar.change': 'Ändern',
    'sidebar.byProcess': 'Nach Prozess',
    'sidebar.byModule': 'Nach Modul',
    'sidebar.complianceJourney': 'Compliance-Reise',
    'sidebar.intelligence': 'Intelligenz',
    'sidebar.coreModules': 'Kernmodule',
    'sidebar.regulatoryModules': 'Regulatorische Module',
    'sidebar.settings': 'Einstellungen',
    'sidebar.availableInPlan': 'Verfügbar im {plan}-Plan',

    // Menu Items
    'menu.dashboard': 'Dashboard',
    'menu.understand': 'Verstehen',
    'menu.documents': 'Dokumente',
    'menu.risks': 'Risiken',
    'menu.evidence': 'Beweise',
    'menu.findings': 'Befunde',
    'menu.audit': 'Audit',
    'menu.integrity': 'Integrität',
    'menu.regfeed': 'Regulatorischer Feed',
    'menu.gapAnalysis': 'Lückenanalyse',
    'menu.documentGenerator': 'Dokumentengenerator',
    'menu.riskMap': 'Risikokarte',
    'menu.evidenceCenter': 'Beweiszentrum',
    'menu.capaTracker': 'CAPA-Tracker',
    'menu.auditRoom': 'Auditraum',
    'menu.preAuditAssessment': 'Voraudit-Selbstbewertung',
    'menu.dora': 'DORA',
    'menu.euai': 'EU KI-Gesetz',
    'menu.escalation': 'Eskalationsregeln',
    'menu.integrations': 'Integrationen',
    'menu.settings': 'Einstellungen',
    'menu.assets': 'Asset-Inventar',

    profile: 'Profil',
    exportReport: 'Bericht Exportieren',
    addFramework: 'Framework Hinzufügen',
    overallCompliance: 'Allgemeine Compliance-Gesundheit',
    documentation: 'Dokumentation',
    implementation: 'Implementierung',
    tested: 'Getestet / Wirksam',
    'dashboard.documentation': 'Dokumentation',
    'dashboard.implementation': 'Implementierung',
    'dashboard.tested': 'Getestet / Wirksam',
    autoTracked: 'Auto-verfolgt',
    reviewNeeded: 'Überprüfung erforderlich',
    humanRequired: 'Mensch erforderlich',
    fromLastMonth: 'vom letzten Monat',
    docsPending: 'Dokumente zur Überprüfung',
    controlsUnverified: 'Kontrollen nicht verifiziert',
    controlsUntested: 'Kontrollen nicht getestet',
    'settings.title': 'Einstellungen',
    'settings.subtitle': 'Sprache, Erscheinungsbild, Benachrichtigungen und Automatisierung anpassen.',
    'settings.organizationProfile': 'Organisationsprofil',
    'settings.currentProfile': 'Aktuelles Profil',
    'settings.profile.foundational': 'Grundlegend',
    'settings.profile.established': 'Etabliert',
    'settings.profile.advanced': 'Fortgeschritten',
    'settings.profile.mature': 'Ausgereift',
    'settings.profileDesc.foundational': 'Geführter Modus mit mehr Hilfe und Erklärungen',
    'settings.profileDesc.established': 'Ausgewogener Modus mit Prozess- und Modulanavigation',
    'settings.profileDesc.advanced': 'Modulzentrierter Modus mit weniger Anleitung',
    'settings.profileDesc.mature': 'Hohe Autonomie für fortgeschrittene Teams',
    'settings.languageRegion': 'Sprache & Region',
    'settings.interfaceLanguage': 'Oberflächensprache',
    'settings.controlsUI': 'Steuert die Sprache der gesamten Plattform',
    'settings.dateFormat': 'Datumsformat',
    'settings.dateFormatHelp': 'Wie Daten in der Oberfläche angezeigt werden',
    'settings.timezone': 'Zeitzone',
    'settings.timezoneHelp': 'Wird für Erinnerungen und Zeitstempel verwendet',
    'settings.appearance': 'Erscheinungsbild',
    'settings.darkMode': 'Dunkelmodus',
    'settings.darkModeHelp': 'Zwischen hellem und dunklem Thema wechseln',
    'settings.compactView': 'Kompakte Ansicht',
    'settings.compactViewHelp': 'Abstände in Tabellen und Karten reduzieren',
    'settings.sidebarLabels': 'Seitenleisten-Beschriftungen anzeigen',
    'settings.sidebarLabelsHelp': 'Textlabels in der Navigation anzeigen',
    'settings.notifications': 'Benachrichtigungen',
    'settings.emailNotifications': 'E-Mail-Benachrichtigungen',
    'settings.emailNotificationsHelp': 'Compliance-Warnungen per E-Mail erhalten',
    'settings.capaReminders': 'CAPA-Erinnerungen',
    'settings.capaRemindersHelp': 'Team an überfällige Korrekturmaßnahmen erinnern',
    'settings.regulatoryUpdates': 'Regulatorische Updates',
    'settings.regulatoryUpdatesHelp': 'Bei neuen regulatorischen Änderungen warnen',
    'settings.auditDeadlines': 'Audit-Fristen',
    'settings.auditDeadlinesHelp': 'Vor wichtigen Auditterminen benachrichtigen',
    'settings.automationScheduling': 'Automatisierung & Planung',
    'settings.autoSave': 'Automatisch speichern',
    'settings.autoSaveHelp': 'Änderungen wenn möglich automatisch speichern',
    'settings.autoRunAnalysis': 'Analyse automatisch ausführen',
    'settings.autoRunAnalysisHelp': 'Periodische Lückenanalysen planen',
    'settings.scheduleFrequency': 'Ausführungsfrequenz',
    'settings.scheduleFrequencyHelp': 'Festlegen, wie oft Prüfungen laufen',
    'settings.userManagement': 'Benutzerverwaltung',
    'settings.activeUser': 'Aktiver Benutzer',
    'settings.inviteTeamMember': 'Teammitglied einladen',
  },
  fr: {
    dashboard: 'Tableau de Bord',
    understand: 'Comprendre Ma Situation',
    documents: 'Contrôles de Documents',
    risks: 'Gérer les Risques',
    evidence: 'Collecter des Preuves',
    findings: 'Gérer les Constatations',
    audit: 'Préparer l\'Audit',
    integrity: 'Intégrité de la Conformité',
    regfeed: 'Flux Réglementaire',
    settings: 'Paramètres',
    escalation: 'Règles d\'Escalade',
    integrations: 'Intégrations',
    gapAnalysis: 'Analyse des Écarts',
    documentGenerator: 'Générateur de Documents',
    riskMap: 'Carte des Risques',
    evidenceCenter: 'Centre de Preuves',
    capaTracker: 'Suivi CAPA',
    auditRoom: 'Salle d\'Audit',
    searchPlaceholder: 'Rechercher des contrôles ou des preuves...',
    administrator: 'Administrateur',
    chatPlaceholder: 'Tapez un message...',
    send: 'Envoyer',

    // Header
    'header.searchPlaceholder': 'Rechercher des contrôles ou des preuves...',
    'header.plan': 'Plan',
    'header.viewProfile': 'Voir le Profil',
    'header.settings': 'Paramètres',
    'header.signOut': 'Se Déconnecter',

    // Sidebar
    'sidebar.orgProfile': 'Profil d\'Organisation',
    'sidebar.change': 'Changer',
    'sidebar.byProcess': 'Par Processus',
    'sidebar.byModule': 'Par Module',
    'sidebar.complianceJourney': 'Parcours de Conformité',
    'sidebar.intelligence': 'Intelligence',
    'sidebar.coreModules': 'Modules Principaux',
    'sidebar.regulatoryModules': 'Modules Réglementaires',
    'sidebar.settings': 'Paramètres',
    'sidebar.availableInPlan': 'Disponible dans le Plan {plan}',

    // Menu Items
    'menu.dashboard': 'Tableau de Bord',
    'menu.understand': 'Comprendre',
    'menu.documents': 'Documents',
    'menu.risks': 'Risques',
    'menu.evidence': 'Preuves',
    'menu.findings': 'Constatations',
    'menu.audit': 'Audit',
    'menu.integrity': 'Intégrité',
    'menu.regfeed': 'Flux Réglementaire',
    'menu.gapAnalysis': 'Analyse des Écarts',
    'menu.documentGenerator': 'Générateur de Documents',
    'menu.riskMap': 'Carte des Risques',
    'menu.evidenceCenter': 'Centre de Preuves',
    'menu.capaTracker': 'Suivi CAPA',
    'menu.auditRoom': 'Salle d\'Audit',
    'menu.preAuditAssessment': 'Auto-évaluation Pré-audit',
    'menu.dora': 'DORA',
    'menu.euai': 'Loi UE sur l\'IA',
    'menu.escalation': 'Règles d\'Escalade',
    'menu.integrations': 'Intégrations',
    'menu.settings': 'Paramètres',
    'menu.assets': 'Inventaire des Actifs',

    profile: 'Profil',
    exportReport: 'Exporter le Rapport',
    addFramework: 'Ajouter un Framework',
    overallCompliance: 'Santé Globale de la Conformité',
    documentation: 'Documentation',
    implementation: 'Implémentation',
    tested: 'Testé / Efficace',
    'dashboard.documentation': 'Documentation',
    'dashboard.implementation': 'Implémentation',
    'dashboard.tested': 'Testé / Efficace',
    autoTracked: 'Auto-suivi',
    reviewNeeded: 'Révision nécessaire',
    humanRequired: 'Humain requis',
    fromLastMonth: 'du mois dernier',
    docsPending: 'docs en attente de révision',
    controlsUnverified: 'contrôles non vérifiés',
    controlsUntested: 'contrôles non testés',
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Ajustez la langue, l’apparence, les notifications et l’automatisation.',
    'settings.organizationProfile': 'Profil de l’organisation',
    'settings.currentProfile': 'Profil actuel',
    'settings.profile.foundational': 'Fondamental',
    'settings.profile.established': 'Établi',
    'settings.profile.advanced': 'Avancé',
    'settings.profile.mature': 'Mûr',
    'settings.profileDesc.foundational': 'Mode guidé avec plus d’aide et d’explications',
    'settings.profileDesc.established': 'Mode équilibré avec navigation par processus et modules',
    'settings.profileDesc.advanced': 'Mode centré sur les modules avec moins de guidance',
    'settings.profileDesc.mature': 'Mode très autonome pour équipes avancées',
    'settings.languageRegion': 'Langue & Région',
    'settings.interfaceLanguage': "Langue de l’interface",
    'settings.controlsUI': 'Contrôle la langue de toute la plateforme',
    'settings.dateFormat': 'Format de date',
    'settings.dateFormatHelp': 'Comment les dates sont affichées dans l’interface',
    'settings.timezone': 'Fuseau horaire',
    'settings.timezoneHelp': 'Utilisé pour les rappels et les horodatages',
    'settings.appearance': 'Apparence',
    'settings.darkMode': 'Mode sombre',
    'settings.darkModeHelp': 'Basculer entre le thème clair et sombre',
    'settings.compactView': 'Vue compacte',
    'settings.compactViewHelp': 'Réduire l’espace dans les tableaux et cartes',
    'settings.sidebarLabels': 'Afficher les libellés de la barre latérale',
    'settings.sidebarLabelsHelp': 'Afficher le texte dans la navigation',
    'settings.notifications': 'Notifications',
    'settings.emailNotifications': 'Notifications par e-mail',
    'settings.emailNotificationsHelp': 'Recevoir les alertes de conformité par e-mail',
    'settings.capaReminders': 'Rappels CAPA',
    'settings.capaRemindersHelp': 'Rappeler les actions correctives en retard',
    'settings.regulatoryUpdates': 'Mises à jour réglementaires',
    'settings.regulatoryUpdatesHelp': 'Avertir des nouveaux changements réglementaires',
    'settings.auditDeadlines': 'Délais d’audit',
    'settings.auditDeadlinesHelp': 'Notifier avant les dates clés d’audit',
    'settings.automationScheduling': 'Automatisation & Planification',
    'settings.autoSave': 'Sauvegarde automatique',
    'settings.autoSaveHelp': 'Enregistrer automatiquement quand c’est possible',
    'settings.autoRunAnalysis': 'Analyse automatique',
    'settings.autoRunAnalysisHelp': 'Planifier des analyses d’écart périodiques',
    'settings.scheduleFrequency': 'Fréquence de planification',
    'settings.scheduleFrequencyHelp': 'Choisissez la fréquence des vérifications automatiques',
    'settings.userManagement': 'Gestion des utilisateurs',
    'settings.activeUser': 'Utilisateur actif',
    'settings.inviteTeamMember': 'Inviter un membre de l’équipe',
  },
};
