export type Page = 'dashboard' | 'understand' | 'documents' | 'risks' | 'evidence' | 'findings' | 'audit' | 'integrity' | 'regfeed' | 'dora' | 'euai' | 'escalation' | 'integrations' | 'settings' | 'assets';
export type Language = 'en' | 'es' | 'pt' | 'de' | 'fr';
export type Profile = 'foundational' | 'established' | 'advanced' | 'mature';
export type DateFormat = 'dmy' | 'mdy' | 'ymd';

export const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    understand: 'Understand My Situation',
    documents: 'Document Controls',
    risks: 'Manage Risks',
    evidence: 'Collect Evidence',
    findings: 'Manage Findings',
    audit: 'Prepare for Audit',
    integrity: 'Compliance Integrity',
    regfeed: 'Regulatory Feed',
    settings: 'Settings',
    escalation: 'Escalation Rules',
    integrations: 'Integrations',
    gapAnalysis: 'Gap Analysis',
    documentGenerator: 'Document Generator',
    riskMap: 'Risk Map',
    evidenceCenter: 'Evidence Center',
    capaTracker: 'CAPA Tracker',
    auditRoom: 'Audit Room',

    // Common
    searchPlaceholder: 'Search controls or evidence...',
    administrator: 'Administrator',
    chatPlaceholder: 'Type a message...',
    send: 'Send',

    // Header
    'header.searchPlaceholder': 'Search controls or evidence...',
    'header.plan': 'Plan',
    'header.viewProfile': 'View Profile',
    'header.settings': 'Settings',
    'header.signOut': 'Sign Out',

    // Sidebar
    'sidebar.orgProfile': 'Organization Profile',
    'sidebar.change': 'Change',
    'sidebar.byProcess': 'By Process',
    'sidebar.byModule': 'By Module',
    'sidebar.complianceJourney': 'Compliance Journey',
    'sidebar.intelligence': 'Intelligence',
    'sidebar.coreModules': 'Core Modules',
    'sidebar.regulatoryModules': 'Regulatory Modules',
    'sidebar.settings': 'Settings',
    'sidebar.availableInPlan': 'Available in {plan} Plan',

    // Menu Items
    'menu.dashboard': 'Dashboard',
    'menu.understand': 'Understand',
    'menu.documents': 'Documents',
    'menu.risks': 'Risks',
    'menu.evidence': 'Evidence',
    'menu.findings': 'Findings',
    'menu.audit': 'Audit',
    'menu.integrity': 'Integrity',
    'menu.regfeed': 'Regulatory Feed',
    'menu.gapAnalysis': 'Gap Analysis',
    'menu.documentGenerator': 'Document Generator',
    'menu.riskMap': 'Risk Map',
    'menu.evidenceCenter': 'Evidence Center',
    'menu.capaTracker': 'CAPA Tracker',
    'menu.auditRoom': 'Audit Room',
    'menu.dora': 'DORA',
    'menu.euai': 'EU AI Act',
    'menu.escalation': 'Escalation Rules',
    'menu.integrations': 'Integrations',
    'menu.settings': 'Settings',
    'menu.assets': 'Asset Inventory',

    // Dashboard
    profile: 'Profile',
    exportReport: 'Export Report',
    addFramework: 'Add Framework',
    overallCompliance: 'Overall Compliance Health',
    documentation: 'Documentation',
    implementation: 'Implementation',
    tested: 'Tested / Effective',
    'dashboard.documentation': 'Documentation',
    'dashboard.implementation': 'Implementation',
    'dashboard.tested': 'Tested / Effective',
    autoTracked: 'Auto-tracked',
    reviewNeeded: 'Review needed',
    humanRequired: 'Human required',
    fromLastMonth: 'from last month',
    docsPending: 'docs pending review',
    controlsUnverified: 'controls unverified',
    controlsUntested: 'controls untested',
  },
  es: {
    // Navigation
    dashboard: 'Panel de Control',
    understand: 'Entender Mi Situación',
    documents: 'Controles de Documentos',
    risks: 'Gestionar Riesgos',
    evidence: 'Recopilar Evidencia',
    findings: 'Gestionar Hallazgos',
    audit: 'Preparar Auditoría',
    integrity: 'Integridad de Cumplimiento',
    regfeed: 'Noticias Regulatorias',
    settings: 'Configuración',
    escalation: 'Reglas de Escalación',
    integrations: 'Integraciones',
    gapAnalysis: 'Análisis de Brechas',
    documentGenerator: 'Generador de Documentos',
    riskMap: 'Mapa de Riesgos',
    evidenceCenter: 'Centro de Evidencias',
    capaTracker: 'Seguimiento de CAPA',
    auditRoom: 'Sala de Auditoría',

    // Common
    searchPlaceholder: 'Buscar controles o evidencia...',
    administrator: 'Administrador',
    chatPlaceholder: 'Escribe un mensaje...',
    send: 'Enviar',

    // Header
    'header.searchPlaceholder': 'Buscar controles o evidencia...',
    'header.plan': 'Plan',
    'header.viewProfile': 'Ver Perfil',
    'header.settings': 'Configuración',
    'header.signOut': 'Cerrar Sesión',

    // Sidebar
    'sidebar.orgProfile': 'Perfil de Organización',
    'sidebar.change': 'Cambiar',
    'sidebar.byProcess': 'Por Proceso',
    'sidebar.byModule': 'Por Módulo',
    'sidebar.complianceJourney': 'Viaje de Cumplimiento',
    'sidebar.intelligence': 'Inteligencia',
    'sidebar.coreModules': 'Módulos Principales',
    'sidebar.regulatoryModules': 'Módulos Regulatorios',
    'sidebar.settings': 'Configuración',
    'sidebar.availableInPlan': 'Disponible en Plan {plan}',

    // Menu Items
    'menu.dashboard': 'Panel de Control',
    'menu.understand': 'Entender',
    'menu.documents': 'Documentos',
    'menu.risks': 'Riesgos',
    'menu.evidence': 'Evidencia',
    'menu.findings': 'Hallazgos',
    'menu.audit': 'Auditoría',
    'menu.integrity': 'Integridad',
    'menu.regfeed': 'Noticias Regulatorias',
    'menu.gapAnalysis': 'Análisis de Brechas',
    'menu.documentGenerator': 'Generador de Documentos',
    'menu.riskMap': 'Mapa de Riesgos',
    'menu.evidenceCenter': 'Centro de Evidencias',
    'menu.capaTracker': 'Seguimiento CAPA',
    'menu.auditRoom': 'Sala de Auditoría',
    'menu.dora': 'DORA',
    'menu.euai': 'Ley IA UE',
    'menu.escalation': 'Reglas de Escalación',
    'menu.integrations': 'Integraciones',
    'menu.settings': 'Configuración',
    'menu.assets': 'Inventario de Activos',

    // Dashboard
    profile: 'Perfil',
    exportReport: 'Exportar Reporte',
    addFramework: 'Agregar Framework',
    overallCompliance: 'Estado General de Cumplimiento',
    documentation: 'Documentación',
    implementation: 'Implementación',
    tested: 'Probado / Efectivo',
    'dashboard.documentation': 'Documentación',
    'dashboard.implementation': 'Implementación',
    'dashboard.tested': 'Probado / Efectivo',
    autoTracked: 'Auto-rastreado',
    reviewNeeded: 'Revisión necesaria',
    humanRequired: 'Humano requerido',
    fromLastMonth: 'desde el mes pasado',
    docsPending: 'docs pendientes de revisión',
    controlsUnverified: 'controles sin verificar',
    controlsUntested: 'controles sin probar',
  },
  pt: {
    dashboard: 'Painel',
    understand: 'Entender Minha Situação',
    documents: 'Controles de Documentos',
    risks: 'Gerenciar Riscos',
    evidence: 'Coletar Evidências',
    findings: 'Gerenciar Achados',
    audit: 'Preparar Auditoria',
    integrity: 'Integridade de Conformidade',
    regfeed: 'Feed Regulatório',
    settings: 'Configurações',
    escalation: 'Regras de Escalação',
    integrations: 'Integrações',
    gapAnalysis: 'Análise de Lacunas',
    documentGenerator: 'Gerador de Documentos',
    riskMap: 'Mapa de Riscos',
    evidenceCenter: 'Centro de Evidências',
    capaTracker: 'Rastreador de CAPA',
    auditRoom: 'Sala de Auditoria',
    searchPlaceholder: 'Pesquisar controles ou evidências...',
    administrator: 'Administrador',
    chatPlaceholder: 'Digite uma mensagem...',
    send: 'Enviar',

    // Header
    'header.searchPlaceholder': 'Pesquisar controles ou evidências...',
    'header.plan': 'Plano',
    'header.viewProfile': 'Ver Perfil',
    'header.settings': 'Configurações',
    'header.signOut': 'Sair',

    // Sidebar
    'sidebar.orgProfile': 'Perfil da Organização',
    'sidebar.change': 'Mudar',
    'sidebar.byProcess': 'Por Processo',
    'sidebar.byModule': 'Por Módulo',
    'sidebar.complianceJourney': 'Jornada de Conformidade',
    'sidebar.intelligence': 'Inteligência',
    'sidebar.coreModules': 'Módulos Principais',
    'sidebar.regulatoryModules': 'Módulos Regulatórios',
    'sidebar.settings': 'Configurações',
    'sidebar.availableInPlan': 'Disponível no Plano {plan}',

    // Menu Items
    'menu.dashboard': 'Painel',
    'menu.understand': 'Entender',
    'menu.documents': 'Documentos',
    'menu.risks': 'Riscos',
    'menu.evidence': 'Evidências',
    'menu.findings': 'Achados',
    'menu.audit': 'Auditoria',
    'menu.integrity': 'Integridade',
    'menu.regfeed': 'Feed Regulatório',
    'menu.gapAnalysis': 'Análise de Lacunas',
    'menu.documentGenerator': 'Gerador de Documentos',
    'menu.riskMap': 'Mapa de Riscos',
    'menu.evidenceCenter': 'Centro de Evidências',
    'menu.capaTracker': 'Rastreador CAPA',
    'menu.auditRoom': 'Sala de Auditoria',
    'menu.dora': 'DORA',
    'menu.euai': 'Lei IA UE',
    'menu.escalation': 'Regras de Escalação',
    'menu.integrations': 'Integrações',
    'menu.settings': 'Configurações',
    'menu.assets': 'Inventário de Ativos',

    profile: 'Perfil',
    exportReport: 'Exportar Relatório',
    addFramework: 'Adicionar Framework',
    overallCompliance: 'Saúde Geral de Conformidade',
    documentation: 'Documentação',
    implementation: 'Implementação',
    tested: 'Testado / Efetivo',
    'dashboard.documentation': 'Documentação',
    'dashboard.implementation': 'Implementação',
    'dashboard.tested': 'Testado / Efetivo',
    autoTracked: 'Auto-rastreado',
    reviewNeeded: 'Revisão necessária',
    humanRequired: 'Humano necessário',
    fromLastMonth: 'do mês passado',
    docsPending: 'docs pendentes de revisão',
    controlsUnverified: 'controles não verificados',
    controlsUntested: 'controles não testados',
  },
  de: {
    dashboard: 'Dashboard',
    understand: 'Meine Situation Verstehen',
    documents: 'Dokumentenkontrollen',
    risks: 'Risiken Verwalten',
    evidence: 'Beweise Sammeln',
    findings: 'Befunde Verwalten',
    audit: 'Audit Vorbereiten',
    integrity: 'Compliance-Integrität',
    regfeed: 'Regulatorischer Feed',
    settings: 'Einstellungen',
    escalation: 'Eskalationsregeln',
    integrations: 'Integrationen',
    gapAnalysis: 'Lückenanalyse',
    documentGenerator: 'Dokumentengenerator',
    riskMap: 'Risikokarte',
    evidenceCenter: 'Beweiszentrum',
    capaTracker: 'CAPA-Tracker',
    auditRoom: 'Auditraum',
    searchPlaceholder: 'Kontrollen oder Beweise suchen...',
    administrator: 'Administrator',
    chatPlaceholder: 'Nachricht eingeben...',
    send: 'Senden',

    // Header
    'header.searchPlaceholder': 'Kontrollen oder Beweise suchen...',
    'header.plan': 'Plan',
    'header.viewProfile': 'Profil Anzeigen',
    'header.settings': 'Einstellungen',
    'header.signOut': 'Abmelden',

    // Sidebar
    'sidebar.orgProfile': 'Organisationsprofil',
    'sidebar.change': 'Ändern',
    'sidebar.byProcess': 'Nach Prozess',
    'sidebar.byModule': 'Nach Modul',
    'sidebar.complianceJourney': 'Compliance-Reise',
    'sidebar.intelligence': 'Intelligenz',
    'sidebar.coreModules': 'Kernmodule',
    'sidebar.regulatoryModules': 'Regulatorische Module',
    'sidebar.settings': 'Einstellungen',
    'sidebar.availableInPlan': 'Verfügbar im {plan}-Plan',

    // Menu Items
    'menu.dashboard': 'Dashboard',
    'menu.understand': 'Verstehen',
    'menu.documents': 'Dokumente',
    'menu.risks': 'Risiken',
    'menu.evidence': 'Beweise',
    'menu.findings': 'Befunde',
    'menu.audit': 'Audit',
    'menu.integrity': 'Integrität',
    'menu.regfeed': 'Regulatorischer Feed',
    'menu.gapAnalysis': 'Lückenanalyse',
    'menu.documentGenerator': 'Dokumentengenerator',
    'menu.riskMap': 'Risikokarte',
    'menu.evidenceCenter': 'Beweiszentrum',
    'menu.capaTracker': 'CAPA-Tracker',
    'menu.auditRoom': 'Auditraum',
    'menu.dora': 'DORA',
    'menu.euai': 'EU KI-Gesetz',
    'menu.escalation': 'Eskalationsregeln',
    'menu.integrations': 'Integrationen',
    'menu.settings': 'Einstellungen',
    'menu.assets': 'Asset-Inventar',

    profile: 'Profil',
    exportReport: 'Bericht Exportieren',
    addFramework: 'Framework Hinzufügen',
    overallCompliance: 'Allgemeine Compliance-Gesundheit',
    documentation: 'Dokumentation',
    implementation: 'Implementierung',
    tested: 'Getestet / Wirksam',
    'dashboard.documentation': 'Dokumentation',
    'dashboard.implementation': 'Implementierung',
    'dashboard.tested': 'Getestet / Wirksam',
    autoTracked: 'Auto-verfolgt',
    reviewNeeded: 'Überprüfung erforderlich',
    humanRequired: 'Mensch erforderlich',
    fromLastMonth: 'vom letzten Monat',
    docsPending: 'Dokumente zur Überprüfung',
    controlsUnverified: 'Kontrollen nicht verifiziert',
    controlsUntested: 'Kontrollen nicht getestet',
  },
  fr: {
    dashboard: 'Tableau de Bord',
    understand: 'Comprendre Ma Situation',
    documents: 'Contrôles de Documents',
    risks: 'Gérer les Risques',
    evidence: 'Collecter des Preuves',
    findings: 'Gérer les Constatations',
    audit: 'Préparer l\'Audit',
    integrity: 'Intégrité de la Conformité',
    regfeed: 'Flux Réglementaire',
    settings: 'Paramètres',
    escalation: 'Règles d\'Escalade',
    integrations: 'Intégrations',
    gapAnalysis: 'Analyse des Écarts',
    documentGenerator: 'Générateur de Documents',
    riskMap: 'Carte des Risques',
    evidenceCenter: 'Centre de Preuves',
    capaTracker: 'Suivi CAPA',
    auditRoom: 'Salle d\'Audit',
    searchPlaceholder: 'Rechercher des contrôles ou des preuves...',
    administrator: 'Administrateur',
    chatPlaceholder: 'Tapez un message...',
    send: 'Envoyer',

    // Header
    'header.searchPlaceholder': 'Rechercher des contrôles ou des preuves...',
    'header.plan': 'Plan',
    'header.viewProfile': 'Voir le Profil',
    'header.settings': 'Paramètres',
    'header.signOut': 'Se Déconnecter',

    // Sidebar
    'sidebar.orgProfile': 'Profil d\'Organisation',
    'sidebar.change': 'Changer',
    'sidebar.byProcess': 'Par Processus',
    'sidebar.byModule': 'Par Module',
    'sidebar.complianceJourney': 'Parcours de Conformité',
    'sidebar.intelligence': 'Intelligence',
    'sidebar.coreModules': 'Modules Principaux',
    'sidebar.regulatoryModules': 'Modules Réglementaires',
    'sidebar.settings': 'Paramètres',
    'sidebar.availableInPlan': 'Disponible dans le Plan {plan}',

    // Menu Items
    'menu.dashboard': 'Tableau de Bord',
    'menu.understand': 'Comprendre',
    'menu.documents': 'Documents',
    'menu.risks': 'Risques',
    'menu.evidence': 'Preuves',
    'menu.findings': 'Constatations',
    'menu.audit': 'Audit',
    'menu.integrity': 'Intégrité',
    'menu.regfeed': 'Flux Réglementaire',
    'menu.gapAnalysis': 'Analyse des Écarts',
    'menu.documentGenerator': 'Générateur de Documents',
    'menu.riskMap': 'Carte des Risques',
    'menu.evidenceCenter': 'Centre de Preuves',
    'menu.capaTracker': 'Suivi CAPA',
    'menu.auditRoom': 'Salle d\'Audit',
    'menu.dora': 'DORA',
    'menu.euai': 'Loi UE sur l\'IA',
    'menu.escalation': 'Règles d\'Escalade',
    'menu.integrations': 'Intégrations',
    'menu.settings': 'Paramètres',
    'menu.assets': 'Inventaire des Actifs',

    profile: 'Profil',
    exportReport: 'Exporter le Rapport',
    addFramework: 'Ajouter un Framework',
    overallCompliance: 'Santé Globale de la Conformité',
    documentation: 'Documentation',
    implementation: 'Implémentation',
    tested: 'Testé / Efficace',
    'dashboard.documentation': 'Documentation',
    'dashboard.implementation': 'Implémentation',
    'dashboard.tested': 'Testé / Efficace',
    autoTracked: 'Auto-suivi',
    reviewNeeded: 'Révision nécessaire',
    humanRequired: 'Humain requis',
    fromLastMonth: 'du mois dernier',
    docsPending: 'docs en attente de révision',
    controlsUnverified: 'contrôles non vérifiés',
    controlsUntested: 'contrôles non testés',
  },
};
