export type Page = 'dashboard' | 'understand' | 'documents' | 'risks' | 'evidence' | 'findings' | 'audit' | 'integrity' | 'regfeed' | 'dora' | 'euai' | 'escalation' | 'integrations' | 'settings' | 'assets';
export type Language = 'en' | 'es' | 'pt' | 'de' | 'fr';
export type Profile = 'foundational' | 'established' | 'advanced' | 'mature';
export type DateFormat = 'dmy' | 'mdy' | 'ymd';

export const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    understand: 'Understand My Situation',
    documents: 'Document Controls',
    risks: 'Manage Risks',
    evidence: 'Collect Evidence',
    findings: 'Manage Findings',
    audit: 'Prepare for Audit',
    integrity: 'Compliance Integrity',
    regfeed: 'Regulatory Feed',
    settings: 'Settings',
    escalation: 'Escalation Rules',
    integrations: 'Integrations',
    gapAnalysis: 'Gap Analysis',
    documentGenerator: 'Document Generator',
    riskMap: 'Risk Map',
    evidenceCenter: 'Evidence Center',
    capaTracker: 'CAPA Tracker',
    auditRoom: 'Audit Room',

    // Common
    searchPlaceholder: 'Search controls or evidence...',
    administrator: 'Administrator',
    chatPlaceholder: 'Type a message...',
    send: 'Send',

    // Header
    'header.searchPlaceholder': 'Search controls or evidence...',
    'header.plan': 'Plan',
    'header.viewProfile': 'View Profile',
    'header.settings': 'Settings',
    'header.signOut': 'Sign Out',

    // Sidebar
    'sidebar.orgProfile': 'Organization Profile',
    'sidebar.change': 'Change',
    'sidebar.byProcess': 'By Process',
    'sidebar.byModule': 'By Module',
    'sidebar.complianceJourney': 'Compliance Journey',
    'sidebar.intelligence': 'Intelligence',
    'sidebar.coreModules': 'Core Modules',
    'sidebar.regulatoryModules': 'Regulatory Modules',
    'sidebar.settings': 'Settings',
    'sidebar.availableInPlan': 'Available in {plan} Plan',

    // Menu Items
    'menu.dashboard': 'Dashboard',
    'menu.understand': 'Understand',
    'menu.documents': 'Documents',
    'menu.risks': 'Risks',
    'menu.evidence': 'Evidence',
    'menu.findings': 'Findings',
    'menu.audit': 'Audit',
    'menu.integrity': 'Integrity',
    'menu.regfeed': 'Regulatory Feed',
    'menu.gapAnalysis': 'Gap Analysis',
    'menu.documentGenerator': 'Document Generator',
    'menu.riskMap': 'Risk Map',
    'menu.evidenceCenter': 'Evidence Center',
    'menu.capaTracker': 'CAPA Tracker',
    'menu.auditRoom': 'Audit Room',
    'menu.preAuditAssessment': 'Pre-Audit Self-Assessment',
    'menu.dora': 'DORA',
    'menu.euai': 'EU AI Act',
    'menu.escalation': 'Escalation Rules',
    'menu.integrations': 'Integrations',
    'menu.settings': 'Settings',
    'menu.assets': 'Asset Inventory',

    // Dashboard
    profile: 'Profile',
    exportReport: 'Export Report',
    addFramework: 'Add Framework',
    overallCompliance: 'Overall Compliance Health',
    documentation: 'Documentation',
    implementation: 'Implementation',
    tested: 'Tested / Effective',
    'dashboard.documentation': 'Documentation',
    'dashboard.implementation': 'Implementation',
    'dashboard.tested': 'Tested / Effective',
    autoTracked: 'Auto-tracked',
    reviewNeeded: 'Review needed',
    humanRequired: 'Human required',
    fromLastMonth: 'from last month',
    docsPending: 'docs pending review',
    controlsUnverified: 'controls unverified',
    controlsUntested: 'controls untested',
    'dashboard.overview': 'Overview of your compliance health and progress',
    'dashboard.kpiLoadError': 'Unable to load KPIs',
    'dashboard.loadingKpis': 'Loading KPIs...',
    'dashboard.healthScoreTrend': 'Health Score Trend',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.upcomingTasks': 'Upcoming Tasks',
    'kpi.noData': 'No data available',
    'kpi.compliance': 'Compliance',
    'healthScore.subtitle': 'Backend-calculated compliance readiness',
    'healthScore.readyLevel': 'Ready level',
    'healthScore.status.ready': 'Ready',
    'healthScore.status.in_progress': 'In progress',
    'healthScore.status.at_risk': 'At risk',
    'healthScore.status.critical': 'Critical',
    'dashboard.activity.gapAnalysis': 'Gap analysis completed for ISO 27001',
    'dashboard.activity.evidence': 'Evidence uploaded for A.8.1',
    'dashboard.activity.capa': 'CAPA NC-2024-015 updated',
    'dashboard.activity.risk': 'Risk R-001 treatment plan approved',
    'dashboard.time.2hours': '2 hours ago',
    'dashboard.time.5hours': '5 hours ago',
    'dashboard.time.1day': '1 day ago',
    'dashboard.time.2days': '2 days ago',
    'dashboard.task.evidence': 'Complete evidence for A.9.2',
    'dashboard.task.capa': 'Review CAPA NC-2025-002',
    'dashboard.task.risk': 'Update risk treatment plan',
    'dashboard.task.auditDocs': 'Prepare audit documentation',
    'dashboard.due.today': 'Today',
    'dashboard.due.tomorrow': 'Tomorrow',
    'dashboard.due.thisWeek': 'This week',
    'dashboard.due.nextWeek': 'Next week',
    'dashboard.priority.high': 'HIGH',
    'dashboard.priority.medium': 'MEDIUM',
    'dashboard.priority.low': 'LOW',
    'audit.title': 'Compliance Audit',
    'audit.subtitle': 'Validate your evidence against ISO 27001 standards',
    'audit.fileValidatorTitle': 'Validate File with Agent',
    'audit.dropHint': 'Click or drag a file',
    'audit.dropSubHint': 'PDF, Word, Excel, Text, Images (max 10MB)',
    'audit.processing': 'Processing granular validation...',
    'audit.jobId': 'Job ID',
    'audit.progress': 'Progress',
    'audit.file': 'File',
    'audit.avgCompliance': 'Average compliance',
    'audit.status': 'Status',
    'audit.validationCompleted': 'Validation completed',
    'audit.summary': 'Summary',
    'audit.findingsByChunk': 'Findings by ISO chunk',
    'audit.score': 'Score',
    'audit.relevance': 'Relevance',
    'audit.suggestions': 'Suggestions',
    'audit.failed': 'Granular validation failed.',
    'audit.titleField': 'Audit Title',
    'audit.descriptionField': 'Description',
    'audit.typeField': 'Audit Type',
    'audit.priorityField': 'Priority',
    'audit.evidenceField': 'Evidence',
    'audit.titlePlaceholder': 'Example: Physical Security Assessment',
    'audit.descriptionPlaceholder': 'Brief description of the audit',
    'audit.evidencePlaceholder': 'Describe the evidence to analyze...',
    'audit.type.security': 'Security',
    'audit.type.compliance': 'Compliance',
    'audit.type.operational': 'Operational',
    'audit.type.financial': 'Financial',
    'audit.priority.low': 'Low',
    'audit.priority.medium': 'Medium',
    'audit.priority.high': 'High',
    'audit.priority.critical': 'Critical',
    'audit.validateButton': 'Validate Audit',
    'audit.validatingButton': 'Validating...',
    'audit.resultsTitle': 'Audit Results',
    'audit.checklistTitle': 'Pre-Audit Checklist',
    'audit.checklistSubtitle': 'Backend persistence with auto-save',
    'audit.completed': 'completed',
    'audit.saveNow': 'Save now',
    'audit.checklistSaving': 'Saving...',
    'audit.checklistDirty': 'Pending changes',
    'audit.savedAt': 'Saved',
    'audit.evidenceSeed': 'We have 5 physical servers in the main meeting room. The servers are on the conference table and any visitor can see them.',
    'audit.checklist.pending': 'Pending',
    'audit.checklist.inProgress': 'In progress',
    'audit.checklist.done': 'Done',
    'audit.checklist.blocked': 'Blocked',
    'audit.checklistNotesPlaceholder': 'Evidence notes, observations, or blockers...',
    'audit.openChat': 'Open Chat',
    'audit.closeChat': 'Close Chat',
    'audit.chatPlaceholder': 'Ask the agent...',
    'audit.checklist.PRE-AUD-01': 'Define audit scope and objectives',
    'audit.checklist.PRE-AUD-02': 'Collect key evidence by control',
    'audit.checklist.PRE-AUD-03': 'Confirm owners and responsible parties',
    'audit.checklist.PRE-AUD-04': 'Review open findings and CAPAs',
    'audit.checklist.PRE-AUD-05': 'Run audit dry run simulation',
    'audit.chatGreeting': 'Hi! I am the Audit Agent. I am ready to analyze your compliance evidence and provide validation based on ISO 27001 standards.',
    'audit.chatAnalysisComplete': 'I have completed the audit analysis. Compliance score: {score}%. Status: {status}. I found {count} findings.',
    'audit.chatRiskResponse': 'Critical risks identified include uncontrolled physical access to equipment, lack of MFA, and insufficient credential rotation policies.',
    'audit.chatRecommendationResponse': 'Recommendations: 1) Implement controlled physical access, 2) Enable MFA on all systems, 3) Set credential rotation policies every 90 days.',
    'audit.chatFallback': 'Understood. Based on the audit analysis, I can help you with findings, recommendations, or next steps.',
    'audit.unknownError': 'Unknown error',
    'audit.fileValidationError': 'File validation error',
    'audit.granularValidationStartError': 'Could not start granular validation',
    'audit.checklistLoadError': 'Could not load the checklist',
    'audit.checklistSaveError': 'Could not save the checklist',
    'audit.jobQueued': 'Job queued',
    'audit.validationError': 'Validation error',
    'audit.validationUnknownError': 'Unknown validation error',
    'settings.title': 'Settings',
    'settings.subtitle': 'Tune language, appearance, notifications, and automation for your workspace.',
    'settings.organizationProfile': 'Organization Profile',
    'settings.currentProfile': 'Current profile',
    'settings.profile.foundational': 'Foundational',
    'settings.profile.established': 'Established',
    'settings.profile.advanced': 'Advanced',
    'settings.profile.mature': 'Mature',
    'settings.profileDesc.foundational': 'Guided mode with more help and explanations',
    'settings.profileDesc.established': 'Balanced mode with process and module navigation',
    'settings.profileDesc.advanced': 'Module-first mode with less guidance',
    'settings.profileDesc.mature': 'High-autonomy mode for advanced teams',
    'settings.languageRegion': 'Language & Region',
    'settings.interfaceLanguage': 'Interface language',
    'settings.controlsUI': 'Controls the language used across the platform',
    'settings.dateFormat': 'Date format',
    'settings.dateFormatHelp': 'How dates are displayed in the UI',
    'settings.timezone': 'Timezone',
    'settings.timezoneHelp': 'Used for reminders and timestamps',
    'settings.appearance': 'Appearance',
    'settings.darkMode': 'Dark mode',
    'settings.darkModeHelp': 'Switch between light and dark theme',
    'settings.compactView': 'Compact view',
    'settings.compactViewHelp': 'Reduce spacing in tables and cards',
    'settings.sidebarLabels': 'Show sidebar labels',
    'settings.sidebarLabelsHelp': 'Display text labels in the navigation',
    'settings.notifications': 'Notifications',
    'settings.emailNotifications': 'Email notifications',
    'settings.emailNotificationsHelp': 'Receive compliance alerts by email',
    'settings.capaReminders': 'CAPA reminders',
    'settings.capaRemindersHelp': 'Remind the team about overdue corrective actions',
    'settings.regulatoryUpdates': 'Regulatory updates',
    'settings.regulatoryUpdatesHelp': 'Alert on new regulatory changes',
    'settings.auditDeadlines': 'Audit deadlines',
    'settings.auditDeadlinesHelp': 'Notify before key audit dates',
    'settings.automationScheduling': 'Automation & Scheduling',
    'settings.autoSave': 'Auto-save',
    'settings.autoSaveHelp': 'Save changes automatically when possible',
    'settings.autoRunAnalysis': 'Auto-run analysis',
    'settings.autoRunAnalysisHelp': 'Schedule periodic gap analysis runs',
    'settings.scheduleFrequency': 'Schedule frequency',
    'settings.scheduleFrequencyHelp': 'Choose how often automated checks run',
    'settings.userManagement': 'User management',
    'settings.activeUser': 'Active user',
    'settings.inviteTeamMember': 'Invite team member',

    // Phases
    'phase.1': 'Context & Leadership',
    'phase.2': 'Planning & Risk',
    'phase.3': 'Support & Operations',
    'phase.4': 'Annex A Controls',

    // Phases
    'phase.1': 'Contexto y Liderazgo',
    'phase.2': 'Planificación y Riesgo',
    'phase.3': 'Soporte y Operaciones',
    'phase.4': 'Controles Anexo A',
  },
  es: {
    // Navigation
    dashboard: 'Panel de Control',
    understand: 'Entender Mi Situación',
    documents: 'Controles de Documentos',
    risks: 'Gestionar Riesgos',
    evidence: 'Recopilar Evidencia',
    findings: 'Gestionar Hallazgos',
    audit: 'Preparar Auditoría',
    integrity: 'Integridad de Cumplimiento',
    regfeed: 'Noticias Regulatorias',
    settings: 'Configuración',
    escalation: 'Reglas de Escalación',
    integrations: 'Integraciones',
    gapAnalysis: 'Análisis de Brechas',
    documentGenerator: 'Generador de Documentos',
    riskMap: 'Mapa de Riesgos',
    evidenceCenter: 'Centro de Evidencias',
    capaTracker: 'Seguimiento de CAPA',
    auditRoom: 'Sala de Auditoría',

    // Common
    searchPlaceholder: 'Buscar controles o evidencia...',
    administrator: 'Administrador',
    chatPlaceholder: 'Escribe un mensaje...',
    send: 'Enviar',

    // Header
    'header.searchPlaceholder': 'Buscar controles o evidencia...',
    'header.plan': 'Plan',
    'header.viewProfile': 'Ver Perfil',
    'header.settings': 'Configuración',
    'header.signOut': 'Cerrar Sesión',

    // Sidebar
    'sidebar.orgProfile': 'Perfil de Organización',
    'sidebar.change': 'Cambiar',
    'sidebar.byProcess': 'Por Proceso',
    'sidebar.byModule': 'Por Módulo',
    'sidebar.complianceJourney': 'Viaje de Cumplimiento',
    'sidebar.intelligence': 'Inteligencia',
    'sidebar.coreModules': 'Módulos Principales',
    'sidebar.regulatoryModules': 'Módulos Regulatorios',
    'sidebar.settings': 'Configuración',
    'sidebar.availableInPlan': 'Disponible en Plan {plan}',

    // Menu Items
    'menu.dashboard': 'Panel de Control',
    'menu.understand': 'Entender',
    'menu.documents': 'Documentos',
    'menu.risks': 'Riesgos',
    'menu.evidence': 'Evidencia',
    'menu.findings': 'Hallazgos',
    'menu.audit': 'Auditoría',
    'menu.integrity': 'Integridad',
    'menu.regfeed': 'Noticias Regulatorias',
    'menu.gapAnalysis': 'Análisis de Brechas',
    'menu.documentGenerator': 'Generador de Documentos',
    'menu.riskMap': 'Mapa de Riesgos',
    'menu.evidenceCenter': 'Centro de Evidencias',
    'menu.capaTracker': 'Seguimiento CAPA',
    'menu.auditRoom': 'Sala de Auditoría',
    'menu.preAuditAssessment': 'Autoevaluación Pre-Auditoría',
    'menu.dora': 'DORA',
    'menu.euai': 'Ley IA UE',
    'menu.escalation': 'Reglas de Escalación',
    'menu.integrations': 'Integraciones',
    'menu.settings': 'Configuración',
    'menu.assets': 'Inventario de Activos',

    // Dashboard
    profile: 'Perfil',
    exportReport: 'Exportar Reporte',
    addFramework: 'Agregar Framework',
    overallCompliance: 'Estado General de Cumplimiento',
    documentation: 'Documentación',
    implementation: 'Implementación',
    tested: 'Probado / Efectivo',
    'dashboard.documentation': 'Documentación',
    'dashboard.implementation': 'Implementación',
    'dashboard.tested': 'Probado / Efectivo',
    autoTracked: 'Auto-rastreado',
    reviewNeeded: 'Revisión necesaria',
    humanRequired: 'Humano requerido',
    fromLastMonth: 'desde el mes pasado',
    docsPending: 'docs pendientes de revisión',
    controlsUnverified: 'controles sin verificar',
    controlsUntested: 'controles sin probar',
    'dashboard.overview': 'Resumen de la salud de cumplimiento y progreso',
    'dashboard.kpiLoadError': 'No se pudieron cargar los KPIs',
    'dashboard.loadingKpis': 'Cargando KPIs...',
    'dashboard.healthScoreTrend': 'Tendencia del score de salud',
    'dashboard.recentActivity': 'Actividad reciente',
    'dashboard.upcomingTasks': 'Próximas tareas',
    'kpi.noData': 'No hay datos disponibles',
    'kpi.compliance': 'Cumplimiento',
    'healthScore.subtitle': 'Preparación de cumplimiento calculada por el backend',
    'healthScore.readyLevel': 'Nivel de preparación',
    'healthScore.status.ready': 'Listo',
    'healthScore.status.in_progress': 'En progreso',
    'healthScore.status.at_risk': 'En riesgo',
    'healthScore.status.critical': 'Crítico',
    'dashboard.activity.gapAnalysis': 'Análisis de brechas completado para ISO 27001',
    'dashboard.activity.evidence': 'Evidencia cargada para A.8.1',
    'dashboard.activity.capa': 'CAPA NC-2024-015 actualizada',
    'dashboard.activity.risk': 'Plan de tratamiento del riesgo R-001 aprobado',
    'dashboard.time.2hours': 'hace 2 horas',
    'dashboard.time.5hours': 'hace 5 horas',
    'dashboard.time.1day': 'hace 1 día',
    'dashboard.time.2days': 'hace 2 días',
    'dashboard.task.evidence': 'Completar evidencia para A.9.2',
    'dashboard.task.capa': 'Revisar CAPA NC-2025-002',
    'dashboard.task.risk': 'Actualizar plan de tratamiento de riesgos',
    'dashboard.task.auditDocs': 'Preparar documentación de auditoría',
    'dashboard.due.today': 'Hoy',
    'dashboard.due.tomorrow': 'Mañana',
    'dashboard.due.thisWeek': 'Esta semana',
    'dashboard.due.nextWeek': 'Próxima semana',
    'dashboard.priority.high': 'ALTA',
    'dashboard.priority.medium': 'MEDIA',
    'dashboard.priority.low': 'BAJA',
    'audit.title': 'Auditoría de Cumplimiento',
    'audit.subtitle': 'Valida tu evidencia de conformidad con estándares ISO 27001',
    'audit.fileValidatorTitle': 'Validar Archivo con Agente',
    'audit.dropHint': 'Haz clic o arrastra un archivo',
    'audit.dropSubHint': 'PDF, Word, Excel, Texto, Imágenes (máx 10MB)',
    'audit.processing': 'Procesando validación granular...',
    'audit.jobId': 'Job ID',
    'audit.progress': 'Progreso',
    'audit.file': 'Archivo',
    'audit.avgCompliance': 'Cumplimiento promedio',
    'audit.status': 'Estado',
    'audit.validationCompleted': 'Validación completada',
    'audit.summary': 'Resumen',
    'audit.findingsByChunk': 'Hallazgos por fragmento ISO',
    'audit.score': 'Score',
    'audit.relevance': 'Relevancia',
    'audit.suggestions': 'Sugerencias',
    'audit.failed': 'La validación granular falló.',
    'audit.titleField': 'Título de la Auditoría',
    'audit.descriptionField': 'Descripción',
    'audit.typeField': 'Tipo de Auditoría',
    'audit.priorityField': 'Prioridad',
    'audit.evidenceField': 'Evidencia',
    'audit.titlePlaceholder': 'Ej: Evaluación de Seguridad Física',
    'audit.descriptionPlaceholder': 'Descripción breve de la auditoría',
    'audit.evidencePlaceholder': 'Describe la evidencia a analizar...',
    'audit.type.security': 'Seguridad',
    'audit.type.compliance': 'Cumplimiento',
    'audit.type.operational': 'Operacional',
    'audit.type.financial': 'Financiero',
    'audit.priority.low': 'Baja',
    'audit.priority.medium': 'Media',
    'audit.priority.high': 'Alta',
    'audit.priority.critical': 'Crítica',
    'audit.validateButton': 'Validar Auditoría',
    'audit.validatingButton': 'Validando...',
    'audit.resultsTitle': 'Resultados de Auditoría',
    'audit.checklistTitle': 'Checklist de Pre-Auditoría',
    'audit.checklistSubtitle': 'Persistencia backend con auto-guardado',
    'audit.completed': 'completado',
    'audit.saveNow': 'Guardar ahora',
    'audit.checklistSaving': 'Guardando...',
    'audit.checklistDirty': 'Cambios pendientes',
    'audit.savedAt': 'Guardado',
    'audit.evidenceSeed': 'Tenemos 5 servidores físicos en la sala de reuniones principal. Los servidores están sobre la mesa de conferencias y cualquier visitante puede verlos.',
    'audit.checklist.pending': 'Pendiente',
    'audit.checklist.inProgress': 'En progreso',
    'audit.checklist.done': 'Completado',
    'audit.checklist.blocked': 'Bloqueado',
    'audit.checklistNotesPlaceholder': 'Notas de evidencia, observaciones o bloqueos...',
    'audit.openChat': 'Abrir Chat',
    'audit.closeChat': 'Cerrar Chat',
    'audit.chatPlaceholder': 'Pregunta al agente...',
    'audit.checklist.PRE-AUD-01': 'Definir alcance y objetivos de auditoria',
    'audit.checklist.PRE-AUD-02': 'Recolectar evidencia clave por control',
    'audit.checklist.PRE-AUD-03': 'Confirmar owners y responsables',
    'audit.checklist.PRE-AUD-04': 'Revisar hallazgos abiertos y CAPAs',
    'audit.checklist.PRE-AUD-05': 'Ejecutar simulacion de auditoria (dry run)',
    'audit.chatGreeting': '¡Hola! Soy el Agente de Auditoría. Estoy listo para analizar tu evidencia de cumplimiento y proporcionar validación basada en estándares ISO 27001.',
    'audit.chatAnalysisComplete': 'He completado el análisis de auditoría. Score de cumplimiento: {score}%. Status: {status}. Se encontraron {count} hallazgos.',
    'audit.chatRiskResponse': 'Los riesgos críticos identificados incluyen: acceso físico no controlado a equipamiento, falta de MFA, y políticas de rotación de credenciales insuficientes.',
    'audit.chatRecommendationResponse': 'Te recomiendo: 1) Implementar acceso físico controlado, 2) Activar MFA en todos los sistemas, 3) Establecer políticas de rotación de credenciales cada 90 días.',
    'audit.chatFallback': 'Entendido. Basándome en el análisis de auditoría, puedo ayudarte con consultas sobre hallazgos, recomendaciones, o próximos pasos.',
    'audit.unknownError': 'Error desconocido',
    'audit.fileValidationError': 'Error al validar archivo',
    'audit.granularValidationStartError': 'No se pudo iniciar la validación granular',
    'audit.checklistLoadError': 'No se pudo cargar el checklist',
    'audit.checklistSaveError': 'No se pudo guardar el checklist',
    'audit.jobQueued': 'Job encolado',
    'audit.validationError': 'Error en la validación',
    'audit.validationUnknownError': 'Error desconocido en la validación',
    'settings.title': 'Configuración',
    'settings.subtitle': 'Ajusta idioma, apariencia, notificaciones y automatización del espacio.',
    'settings.organizationProfile': 'Perfil de Organización',
    'settings.currentProfile': 'Perfil actual',
    'settings.profile.foundational': 'Fundacional',
    'settings.profile.established': 'Establecido',
    'settings.profile.advanced': 'Avanzado',
    'settings.profile.mature': 'Maduro',
    'settings.profileDesc.foundational': 'Modo guiado con más ayuda y explicaciones',
    'settings.profileDesc.established': 'Modo equilibrado con navegación por proceso y módulos',
    'settings.profileDesc.advanced': 'Modo centrado en módulos con menos guía',
    'settings.profileDesc.mature': 'Modo de alta autonomía para equipos avanzados',
    'settings.languageRegion': 'Idioma y Región',
    'settings.interfaceLanguage': 'Idioma de la interfaz',
    'settings.controlsUI': 'Controla el idioma de toda la plataforma',
    'settings.dateFormat': 'Formato de fecha',
    'settings.dateFormatHelp': 'Cómo se muestran las fechas en la interfaz',
    'settings.timezone': 'Zona horaria',
    'settings.timezoneHelp': 'Usada para recordatorios y marcas de tiempo',
    'settings.appearance': 'Apariencia',
    'settings.darkMode': 'Modo oscuro',
    'settings.darkModeHelp': 'Alterna entre tema claro y oscuro',
    'settings.compactView': 'Vista compacta',
    'settings.compactViewHelp': 'Reduce el espacio en tablas y tarjetas',
    'settings.sidebarLabels': 'Mostrar etiquetas del menú',
    'settings.sidebarLabelsHelp': 'Muestra texto en la navegación lateral',
    'settings.notifications': 'Notificaciones',
    'settings.emailNotifications': 'Notificaciones por correo',
    'settings.emailNotificationsHelp': 'Recibe alertas de cumplimiento por correo',
    'settings.capaReminders': 'Recordatorios CAPA',
    'settings.capaRemindersHelp': 'Recuerda acciones correctivas vencidas',
    'settings.regulatoryUpdates': 'Actualizaciones regulatorias',
    'settings.regulatoryUpdatesHelp': 'Avísame cuando haya cambios regulatorios',
    'settings.auditDeadlines': 'Fechas de auditoría',
    'settings.auditDeadlinesHelp': 'Notifica antes de fechas clave',
    'settings.automationScheduling': 'Automatización y programación',
    'settings.autoSave': 'Guardado automático',
    'settings.autoSaveHelp': 'Guarda cambios automáticamente cuando sea posible',
    'settings.autoRunAnalysis': 'Ejecutar análisis automático',
    'settings.autoRunAnalysisHelp': 'Programa análisis de brechas periódicos',
    'settings.scheduleFrequency': 'Frecuencia de ejecución',
    'settings.scheduleFrequencyHelp': 'Elige cada cuánto se ejecutan las revisiones',
    'settings.userManagement': 'Gestión de usuarios',
    'settings.activeUser': 'Usuario activo',
    'settings.inviteTeamMember': 'Invitar miembro del equipo',
  },
  pt: {
    dashboard: 'Painel',
    understand: 'Entender Minha Situação',
    documents: 'Controles de Documentos',
    risks: 'Gerenciar Riscos',
    evidence: 'Coletar Evidências',
    findings: 'Gerenciar Achados',
    audit: 'Preparar Auditoria',
    integrity: 'Integridade de Conformidade',
    regfeed: 'Feed Regulatório',
    settings: 'Configurações',
    escalation: 'Regras de Escalação',
    integrations: 'Integrações',
    gapAnalysis: 'Análise de Lacunas',
    documentGenerator: 'Gerador de Documentos',
    riskMap: 'Mapa de Riscos',
    evidenceCenter: 'Centro de Evidências',
    capaTracker: 'Rastreador de CAPA',
    auditRoom: 'Sala de Auditoria',
    'menu.preAuditAssessment': 'Autoavaliação Pré-Auditoria',
    searchPlaceholder: 'Pesquisar controles ou evidências...',
    administrator: 'Administrador',
    chatPlaceholder: 'Digite uma mensagem...',
    send: 'Enviar',

    // Header
    'header.searchPlaceholder': 'Pesquisar controles ou evidências...',
    'header.plan': 'Plano',
    'header.viewProfile': 'Ver Perfil',
    'header.settings': 'Configurações',
    'header.signOut': 'Sair',

    // Sidebar
    'sidebar.orgProfile': 'Perfil da Organização',
    'sidebar.change': 'Mudar',
    'sidebar.byProcess': 'Por Processo',
    'sidebar.byModule': 'Por Módulo',
    'sidebar.complianceJourney': 'Jornada de Conformidade',
    'sidebar.intelligence': 'Inteligência',
    'sidebar.coreModules': 'Módulos Principais',
    'sidebar.regulatoryModules': 'Módulos Regulatórios',
    'sidebar.settings': 'Configurações',
    'sidebar.availableInPlan': 'Disponível no Plano {plan}',

    // Menu Items
    'menu.dashboard': 'Painel',
    'menu.understand': 'Entender',
    'menu.documents': 'Documentos',
    'menu.risks': 'Riscos',
    'menu.evidence': 'Evidências',
    'menu.findings': 'Achados',
    'menu.audit': 'Auditoria',
    'menu.integrity': 'Integridade',
    'menu.regfeed': 'Feed Regulatório',
    'menu.gapAnalysis': 'Análise de Lacunas',
    'menu.documentGenerator': 'Gerador de Documentos',
    'menu.riskMap': 'Mapa de Riscos',
    'menu.evidenceCenter': 'Centro de Evidências',
    'menu.capaTracker': 'Rastreador CAPA',
    'menu.auditRoom': 'Sala de Auditoria',
    'menu.dora': 'DORA',
    'menu.euai': 'Lei IA UE',
    'menu.escalation': 'Regras de Escalação',
    'menu.integrations': 'Integrações',
    'menu.settings': 'Configurações',
    'menu.assets': 'Inventário de Ativos',

    profile: 'Perfil',
    exportReport: 'Exportar Relatório',
    addFramework: 'Adicionar Framework',
    overallCompliance: 'Saúde Geral de Conformidade',
    documentation: 'Documentação',
    implementation: 'Implementação',
    tested: 'Testado / Efetivo',
    'dashboard.documentation': 'Documentação',
    'dashboard.implementation': 'Implementação',
    'dashboard.tested': 'Testado / Efetivo',
    autoTracked: 'Auto-rastreado',
    reviewNeeded: 'Revisão necessária',
    humanRequired: 'Humano necessário',
    fromLastMonth: 'do mês passado',
    docsPending: 'docs pendentes de revisão',
    controlsUnverified: 'controles não verificados',
    controlsUntested: 'controles não testados',
    'dashboard.overview': 'Visão geral da saúde de conformidade e do progresso',
    'dashboard.kpiLoadError': 'Não foi possível carregar os KPIs',
    'dashboard.loadingKpis': 'Carregando KPIs...',
    'dashboard.healthScoreTrend': 'Tendência da pontuação de saúde',
    'dashboard.recentActivity': 'Atividade recente',
    'dashboard.upcomingTasks': 'Próximas tarefas',
    'kpi.noData': 'Não há dados disponíveis',
    'kpi.compliance': 'Conformidade',
    'healthScore.subtitle': 'Prontidão de conformidade calculada pelo backend',
    'healthScore.readyLevel': 'Nível de prontidão',
    'healthScore.status.ready': 'Pronto',
    'healthScore.status.in_progress': 'Em andamento',
    'healthScore.status.at_risk': 'Em risco',
    'healthScore.status.critical': 'Crítico',
    'dashboard.activity.gapAnalysis': 'Análise de lacunas concluída para ISO 27001',
    'dashboard.activity.evidence': 'Evidência carregada para A.8.1',
    'dashboard.activity.capa': 'CAPA NC-2024-015 atualizada',
    'dashboard.activity.risk': 'Plano de tratamento do risco R-001 aprovado',
    'dashboard.time.2hours': 'há 2 horas',
    'dashboard.time.5hours': 'há 5 horas',
    'dashboard.time.1day': 'há 1 dia',
    'dashboard.time.2days': 'há 2 dias',
    'dashboard.task.evidence': 'Concluir evidência para A.9.2',
    'dashboard.task.capa': 'Revisar CAPA NC-2025-002',
    'dashboard.task.risk': 'Atualizar plano de tratamento de riscos',
    'dashboard.task.auditDocs': 'Preparar documentação de auditoria',
    'dashboard.due.today': 'Hoje',
    'dashboard.due.tomorrow': 'Amanhã',
    'dashboard.due.thisWeek': 'Esta semana',
    'dashboard.due.nextWeek': 'Próxima semana',
    'dashboard.priority.high': 'ALTA',
    'dashboard.priority.medium': 'MÉDIA',
    'dashboard.priority.low': 'BAIXA',
    'audit.title': 'Auditoria de Conformidade',
    'audit.subtitle': 'Valide sua evidência de conformidade com os padrões ISO 27001',
    'audit.fileValidatorTitle': 'Validar arquivo com agente',
    'audit.dropHint': 'Clique ou arraste um arquivo',
    'audit.dropSubHint': 'PDF, Word, Excel, Texto, Imagens (máx. 10MB)',
    'audit.processing': 'Processando validação granular...',
    'audit.jobId': 'ID do trabalho',
    'audit.progress': 'Progresso',
    'audit.file': 'Arquivo',
    'audit.avgCompliance': 'Conformidade média',
    'audit.status': 'Status',
    'audit.validationCompleted': 'Validação concluída',
    'audit.summary': 'Resumo',
    'audit.findingsByChunk': 'Achados por trecho ISO',
    'audit.score': 'Pontuação',
    'audit.relevance': 'Relevância',
    'audit.suggestions': 'Sugestões',
    'audit.failed': 'A validação granular falhou.',
    'audit.titleField': 'Título da auditoria',
    'audit.descriptionField': 'Descrição',
    'audit.typeField': 'Tipo de auditoria',
    'audit.priorityField': 'Prioridade',
    'audit.evidenceField': 'Evidência',
    'audit.titlePlaceholder': 'Ex.: Avaliação de Segurança Física',
    'audit.descriptionPlaceholder': 'Breve descrição da auditoria',
    'audit.evidencePlaceholder': 'Descreva a evidência a analisar...',
    'audit.type.security': 'Segurança',
    'audit.type.compliance': 'Conformidade',
    'audit.type.operational': 'Operacional',
    'audit.type.financial': 'Financeiro',
    'audit.priority.low': 'Baixa',
    'audit.priority.medium': 'Média',
    'audit.priority.high': 'Alta',
    'audit.priority.critical': 'Crítica',
    'audit.validateButton': 'Validar auditoria',
    'audit.validatingButton': 'Validando...',
    'audit.resultsTitle': 'Resultados da auditoria',
    'audit.checklistTitle': 'Checklist de Pré-Auditoria',
    'audit.checklistSubtitle': 'Persistência no backend com salvamento automático',
    'audit.completed': 'concluído',
    'audit.saveNow': 'Salvar agora',
    'audit.checklistSaving': 'Salvando...',
    'audit.checklistDirty': 'Alterações pendentes',
    'audit.savedAt': 'Salvo',
    'audit.evidenceSeed': 'Temos 5 servidores físicos na sala principal de reuniões. Os servidores estão sobre a mesa de conferência e qualquer visitante pode vê-los.',
    'audit.checklist.pending': 'Pendente',
    'audit.checklist.inProgress': 'Em andamento',
    'audit.checklist.done': 'Concluído',
    'audit.checklist.blocked': 'Bloqueado',
    'audit.checklistNotesPlaceholder': 'Notas de evidência, observações ou bloqueios...',
    'audit.openChat': 'Abrir chat',
    'audit.closeChat': 'Fechar chat',
    'audit.chatPlaceholder': 'Pergunte ao agente...',
    'audit.checklist.PRE-AUD-01': 'Definir escopo e objetivos da auditoria',
    'audit.checklist.PRE-AUD-02': 'Coletar evidências-chave por controle',
    'audit.checklist.PRE-AUD-03': 'Confirmar responsáveis e owners',
    'audit.checklist.PRE-AUD-04': 'Revisar achados abertos e CAPAs',
    'audit.checklist.PRE-AUD-05': 'Executar simulação de auditoria (dry run)',
    'audit.chatGreeting': 'Olá! Sou o Agente de Auditoria. Estou pronto para analisar sua evidência de conformidade e fornecer validação com base nos padrões ISO 27001.',
    'audit.chatAnalysisComplete': 'Concluí a análise de auditoria. Pontuação de conformidade: {score}%. Status: {status}. Encontrei {count} achados.',
    'audit.chatRiskResponse': 'Os riscos críticos identificados incluem acesso físico não controlado ao equipamento, falta de MFA e políticas insuficientes de rotação de credenciais.',
    'audit.chatRecommendationResponse': 'Recomendações: 1) Implementar acesso físico controlado, 2) Ativar MFA em todos os sistemas, 3) Estabelecer políticas de rotação de credenciais a cada 90 dias.',
    'audit.chatFallback': 'Entendido. Com base na análise de auditoria, posso ajudar com achados, recomendações ou próximos passos.',
    'audit.unknownError': 'Erro desconhecido',
    'audit.fileValidationError': 'Erro ao validar arquivo',
    'audit.granularValidationStartError': 'Não foi possível iniciar a validação granular',
    'audit.checklistLoadError': 'Não foi possível carregar o checklist',
    'audit.checklistSaveError': 'Não foi possível salvar o checklist',
    'audit.jobQueued': 'Trabalho enfileirado',
    'audit.validationError': 'Erro de validação',
    'audit.validationUnknownError': 'Erro de validação desconhecido',
    'settings.title': 'Configurações',
    'settings.subtitle': 'Ajuste idioma, aparência, notificações e automação do seu espaço.',
    'settings.organizationProfile': 'Perfil da Organização',
    'settings.currentProfile': 'Perfil atual',
    'settings.profile.foundational': 'Fundacional',
    'settings.profile.established': 'Estabelecido',
    'settings.profile.advanced': 'Avançado',
    'settings.profile.mature': 'Maduro',
    'settings.profileDesc.foundational': 'Modo guiado com mais ajuda e explicações',
    'settings.profileDesc.established': 'Modo equilibrado com navegação por processo e módulos',
    'settings.profileDesc.advanced': 'Modo focado em módulos com menos orientação',
    'settings.profileDesc.mature': 'Modo de alta autonomia para equipes avançadas',
    'settings.languageRegion': 'Idioma e Região',
    'settings.interfaceLanguage': 'Idioma da interface',
    'settings.controlsUI': 'Controla o idioma de toda a plataforma',
    'settings.dateFormat': 'Formato de data',
    'settings.dateFormatHelp': 'Como as datas são exibidas na interface',
    'settings.timezone': 'Fuso horário',
    'settings.timezoneHelp': 'Usado para lembretes e horários',
    'settings.appearance': 'Aparência',
    'settings.darkMode': 'Modo escuro',
    'settings.darkModeHelp': 'Alterna entre tema claro e escuro',
    'settings.compactView': 'Visualização compacta',
    'settings.compactViewHelp': 'Reduz o espaço em tabelas e cartões',
    'settings.sidebarLabels': 'Mostrar rótulos da barra lateral',
    'settings.sidebarLabelsHelp': 'Exibe texto na navegação lateral',
    'settings.notifications': 'Notificações',
    'settings.emailNotifications': 'Notificações por e-mail',
    'settings.emailNotificationsHelp': 'Receba alertas de conformidade por e-mail',
    'settings.capaReminders': 'Lembretes CAPA',
    'settings.capaRemindersHelp': 'Lembra a equipe sobre ações corretivas vencidas',
    'settings.regulatoryUpdates': 'Atualizações regulatórias',
    'settings.regulatoryUpdatesHelp': 'Alertar sobre novas mudanças regulatórias',
    'settings.auditDeadlines': 'Prazos de auditoria',
    'settings.auditDeadlinesHelp': 'Notificar antes das datas-chave de auditoria',
    'settings.automationScheduling': 'Automação e Agendamento',
    'settings.autoSave': 'Salvamento automático',
    'settings.autoSaveHelp': 'Salva alterações automaticamente quando possível',
    'settings.autoRunAnalysis': 'Executar análise automática',
    'settings.autoRunAnalysisHelp': 'Agende análises periódicas de lacunas',
    'settings.scheduleFrequency': 'Frequência de execução',
    'settings.scheduleFrequencyHelp': 'Escolha com que frequência as verificações rodam',
    'settings.userManagement': 'Gestão de usuários',
    'settings.activeUser': 'Usuário ativo',
    'settings.inviteTeamMember': 'Convidar membro da equipe',
  },
  de: {
    dashboard: 'Dashboard',
    understand: 'Meine Situation Verstehen',
    documents: 'Dokumentenkontrollen',
    risks: 'Risiken Verwalten',
    evidence: 'Beweise Sammeln',
    findings: 'Befunde Verwalten',
    audit: 'Audit Vorbereiten',
    integrity: 'Compliance-Integrität',
    regfeed: 'Regulatorischer Feed',
    settings: 'Einstellungen',
    escalation: 'Eskalationsregeln',
    integrations: 'Integrationen',
    gapAnalysis: 'Lückenanalyse',
    documentGenerator: 'Dokumentengenerator',
    riskMap: 'Risikokarte',
    evidenceCenter: 'Beweiszentrum',
    capaTracker: 'CAPA-Tracker',
    auditRoom: 'Auditraum',
    searchPlaceholder: 'Kontrollen oder Beweise suchen...',
    administrator: 'Administrator',
    chatPlaceholder: 'Nachricht eingeben...',
    send: 'Senden',

    // Header
    'header.searchPlaceholder': 'Kontrollen oder Beweise suchen...',
    'header.plan': 'Plan',
    'header.viewProfile': 'Profil Anzeigen',
    'header.settings': 'Einstellungen',
    'header.signOut': 'Abmelden',

    // Sidebar
    'sidebar.orgProfile': 'Organisationsprofil',
    'sidebar.change': 'Ändern',
    'sidebar.byProcess': 'Nach Prozess',
    'sidebar.byModule': 'Nach Modul',
    'sidebar.complianceJourney': 'Compliance-Reise',
    'sidebar.intelligence': 'Intelligenz',
    'sidebar.coreModules': 'Kernmodule',
    'sidebar.regulatoryModules': 'Regulatorische Module',
    'sidebar.settings': 'Einstellungen',
    'sidebar.availableInPlan': 'Verfügbar im {plan}-Plan',

    // Menu Items
    'menu.dashboard': 'Dashboard',
    'menu.understand': 'Verstehen',
    'menu.documents': 'Dokumente',
    'menu.risks': 'Risiken',
    'menu.evidence': 'Beweise',
    'menu.findings': 'Befunde',
    'menu.audit': 'Audit',
    'menu.integrity': 'Integrität',
    'menu.regfeed': 'Regulatorischer Feed',
    'menu.gapAnalysis': 'Lückenanalyse',
    'menu.documentGenerator': 'Dokumentengenerator',
    'menu.riskMap': 'Risikokarte',
    'menu.evidenceCenter': 'Beweiszentrum',
    'menu.capaTracker': 'CAPA-Tracker',
    'menu.auditRoom': 'Auditraum',
    'menu.preAuditAssessment': 'Voraudit-Selbstbewertung',
    'menu.dora': 'DORA',
    'menu.euai': 'EU KI-Gesetz',
    'menu.escalation': 'Eskalationsregeln',
    'menu.integrations': 'Integrationen',
    'menu.settings': 'Einstellungen',
    'menu.assets': 'Asset-Inventar',

    profile: 'Profil',
    exportReport: 'Bericht Exportieren',
    addFramework: 'Framework Hinzufügen',
    overallCompliance: 'Allgemeine Compliance-Gesundheit',
    documentation: 'Dokumentation',
    implementation: 'Implementierung',
    tested: 'Getestet / Wirksam',
    'dashboard.documentation': 'Dokumentation',
    'dashboard.implementation': 'Implementierung',
    'dashboard.tested': 'Getestet / Wirksam',
    autoTracked: 'Auto-verfolgt',
    reviewNeeded: 'Überprüfung erforderlich',
    humanRequired: 'Mensch erforderlich',
    fromLastMonth: 'vom letzten Monat',
    docsPending: 'Dokumente zur Überprüfung',
    controlsUnverified: 'Kontrollen nicht verifiziert',
    controlsUntested: 'Kontrollen nicht getestet',
    'dashboard.overview': 'Überblick über Compliance-Gesundheit und Fortschritt',
    'dashboard.kpiLoadError': 'KPIs konnten nicht geladen werden',
    'dashboard.loadingKpis': 'KPIs werden geladen...',
    'dashboard.healthScoreTrend': 'Trend des Gesundheits-Scores',
    'dashboard.recentActivity': 'Letzte Aktivitäten',
    'dashboard.upcomingTasks': 'Anstehende Aufgaben',
    'kpi.noData': 'Keine Daten verfügbar',
    'kpi.compliance': 'Compliance',
    'healthScore.subtitle': 'Vom Backend berechnete Compliance-Bereitschaft',
    'healthScore.readyLevel': 'Bereitschaftsgrad',
    'healthScore.status.ready': 'Bereit',
    'healthScore.status.in_progress': 'In Bearbeitung',
    'healthScore.status.at_risk': 'Gefährdet',
    'healthScore.status.critical': 'Kritisch',
    'dashboard.activity.gapAnalysis': 'Lückenanalyse für ISO 27001 abgeschlossen',
    'dashboard.activity.evidence': 'Nachweis für A.8.1 hochgeladen',
    'dashboard.activity.capa': 'CAPA NC-2024-015 aktualisiert',
    'dashboard.activity.risk': 'Behandlungsplan für Risiko R-001 genehmigt',
    'dashboard.time.2hours': 'vor 2 Stunden',
    'dashboard.time.5hours': 'vor 5 Stunden',
    'dashboard.time.1day': 'vor 1 Tag',
    'dashboard.time.2days': 'vor 2 Tagen',
    'dashboard.task.evidence': 'Nachweis für A.9.2 vervollständigen',
    'dashboard.task.capa': 'CAPA NC-2025-002 prüfen',
    'dashboard.task.risk': 'Risikobehandlungsplan aktualisieren',
    'dashboard.task.auditDocs': 'Auditschrift vorbereiten',
    'dashboard.due.today': 'Heute',
    'dashboard.due.tomorrow': 'Morgen',
    'dashboard.due.thisWeek': 'Diese Woche',
    'dashboard.due.nextWeek': 'Nächste Woche',
    'dashboard.priority.high': 'HOCH',
    'dashboard.priority.medium': 'MITTEL',
    'dashboard.priority.low': 'NIEDRIG',
    'audit.title': 'Compliance-Audit',
    'audit.subtitle': 'Validieren Sie Ihre Nachweise anhand der ISO-27001-Standards',
    'audit.fileValidatorTitle': 'Datei mit Agent validieren',
    'audit.dropHint': 'Klicken oder ziehen Sie eine Datei',
    'audit.dropSubHint': 'PDF, Word, Excel, Text, Bilder (max. 10 MB)',
    'audit.processing': 'Granulare Validierung wird verarbeitet...',
    'audit.jobId': 'Job-ID',
    'audit.progress': 'Fortschritt',
    'audit.file': 'Datei',
    'audit.avgCompliance': 'Durchschnittliche Compliance',
    'audit.status': 'Status',
    'audit.validationCompleted': 'Validierung abgeschlossen',
    'audit.summary': 'Zusammenfassung',
    'audit.findingsByChunk': 'Ergebnisse nach ISO-Abschnitt',
    'audit.score': 'Wert',
    'audit.relevance': 'Relevanz',
    'audit.suggestions': 'Vorschläge',
    'audit.failed': 'Die granulare Validierung ist fehlgeschlagen.',
    'audit.titleField': 'Audittitel',
    'audit.descriptionField': 'Beschreibung',
    'audit.typeField': 'Audittyp',
    'audit.priorityField': 'Priorität',
    'audit.evidenceField': 'Nachweis',
    'audit.titlePlaceholder': 'z. B. Physische Sicherheitsbewertung',
    'audit.descriptionPlaceholder': 'Kurze Beschreibung des Audits',
    'audit.evidencePlaceholder': 'Beschreiben Sie die zu analysierenden Nachweise...',
    'audit.type.security': 'Sicherheit',
    'audit.type.compliance': 'Compliance',
    'audit.type.operational': 'Betrieblich',
    'audit.type.financial': 'Finanziell',
    'audit.priority.low': 'Niedrig',
    'audit.priority.medium': 'Mittel',
    'audit.priority.high': 'Hoch',
    'audit.priority.critical': 'Kritisch',
    'audit.validateButton': 'Audit validieren',
    'audit.validatingButton': 'Validierung läuft...',
    'audit.resultsTitle': 'Auditergebnisse',
    'audit.checklistTitle': 'Pre-Audit-Checkliste',
    'audit.checklistSubtitle': 'Backend-Persistenz mit automatischem Speichern',
    'audit.completed': 'abgeschlossen',
    'audit.saveNow': 'Jetzt speichern',
    'audit.checklistSaving': 'Wird gespeichert...',
    'audit.checklistDirty': 'Ausstehende Änderungen',
    'audit.savedAt': 'Gespeichert',
    'audit.evidenceSeed': 'Wir haben 5 physische Server im Hauptbesprechungsraum. Die Server stehen auf dem Konferenztisch und jeder Besucher kann sie sehen.',
    'audit.checklist.pending': 'Ausstehend',
    'audit.checklist.inProgress': 'In Bearbeitung',
    'audit.checklist.done': 'Erledigt',
    'audit.checklist.blocked': 'Blockiert',
    'audit.checklistNotesPlaceholder': 'Nachweishinweise, Beobachtungen oder Blocker...',
    'audit.openChat': 'Chat öffnen',
    'audit.closeChat': 'Chat schließen',
    'audit.chatPlaceholder': 'Fragen Sie den Agenten...',
    'audit.checklist.PRE-AUD-01': 'Umfang und Ziele des Audits definieren',
    'audit.checklist.PRE-AUD-02': 'Wichtige Nachweise je Kontrolle erfassen',
    'audit.checklist.PRE-AUD-03': 'Verantwortliche und Zuständige bestätigen',
    'audit.checklist.PRE-AUD-04': 'Offene Befunde und CAPAs prüfen',
    'audit.checklist.PRE-AUD-05': 'Audit-Dry-Run-Simulation durchführen',
    'audit.chatGreeting': 'Hallo! Ich bin der Audit-Agent. Ich bin bereit, Ihre Compliance-Nachweise zu analysieren und eine Validierung auf Basis der ISO-27001-Standards bereitzustellen.',
    'audit.chatAnalysisComplete': 'Ich habe die Audit-Analyse abgeschlossen. Compliance-Score: {score}%. Status: {status}. Ich habe {count} Befunde gefunden.',
    'audit.chatRiskResponse': 'Zu den kritischen Risiken zählen unkontrollierter physischer Zugriff auf Geräte, fehlendes MFA und unzureichende Richtlinien zur Credential-Rotation.',
    'audit.chatRecommendationResponse': 'Empfehlungen: 1) Kontrollierten physischen Zugriff einführen, 2) MFA auf allen Systemen aktivieren, 3) Richtlinien zur Credential-Rotation alle 90 Tage festlegen.',
    'audit.chatFallback': 'Verstanden. Auf Basis der Audit-Analyse kann ich bei Befunden, Empfehlungen oder den nächsten Schritten helfen.',
    'audit.unknownError': 'Unbekannter Fehler',
    'audit.fileValidationError': 'Fehler bei der Dateivalidierung',
    'audit.granularValidationStartError': 'Granulare Validierung konnte nicht gestartet werden',
    'audit.checklistLoadError': 'Die Checkliste konnte nicht geladen werden',
    'audit.checklistSaveError': 'Die Checkliste konnte nicht gespeichert werden',
    'audit.jobQueued': 'Job in Warteschlange',
    'audit.validationError': 'Validierungsfehler',
    'audit.validationUnknownError': 'Unbekannter Validierungsfehler',
    'settings.title': 'Einstellungen',
    'settings.subtitle': 'Sprache, Erscheinungsbild, Benachrichtigungen und Automatisierung anpassen.',
    'settings.organizationProfile': 'Organisationsprofil',
    'settings.currentProfile': 'Aktuelles Profil',
    'settings.profile.foundational': 'Grundlegend',
    'settings.profile.established': 'Etabliert',
    'settings.profile.advanced': 'Fortgeschritten',
    'settings.profile.mature': 'Ausgereift',
    'settings.profileDesc.foundational': 'Geführter Modus mit mehr Hilfe und Erklärungen',
    'settings.profileDesc.established': 'Ausgewogener Modus mit Prozess- und Modulanavigation',
    'settings.profileDesc.advanced': 'Modulzentrierter Modus mit weniger Anleitung',
    'settings.profileDesc.mature': 'Hohe Autonomie für fortgeschrittene Teams',
    'settings.languageRegion': 'Sprache & Region',
    'settings.interfaceLanguage': 'Oberflächensprache',
    'settings.controlsUI': 'Steuert die Sprache der gesamten Plattform',
    'settings.dateFormat': 'Datumsformat',
    'settings.dateFormatHelp': 'Wie Daten in der Oberfläche angezeigt werden',
    'settings.timezone': 'Zeitzone',
    'settings.timezoneHelp': 'Wird für Erinnerungen und Zeitstempel verwendet',
    'settings.appearance': 'Erscheinungsbild',
    'settings.darkMode': 'Dunkelmodus',
    'settings.darkModeHelp': 'Zwischen hellem und dunklem Thema wechseln',
    'settings.compactView': 'Kompakte Ansicht',
    'settings.compactViewHelp': 'Abstände in Tabellen und Karten reduzieren',
    'settings.sidebarLabels': 'Seitenleisten-Beschriftungen anzeigen',
    'settings.sidebarLabelsHelp': 'Textlabels in der Navigation anzeigen',
    'settings.notifications': 'Benachrichtigungen',
    'settings.emailNotifications': 'E-Mail-Benachrichtigungen',
    'settings.emailNotificationsHelp': 'Compliance-Warnungen per E-Mail erhalten',
    'settings.capaReminders': 'CAPA-Erinnerungen',
    'settings.capaRemindersHelp': 'Team an überfällige Korrekturmaßnahmen erinnern',
    'settings.regulatoryUpdates': 'Regulatorische Updates',
    'settings.regulatoryUpdatesHelp': 'Bei neuen regulatorischen Änderungen warnen',
    'settings.auditDeadlines': 'Audit-Fristen',
    'settings.auditDeadlinesHelp': 'Vor wichtigen Auditterminen benachrichtigen',
    'settings.automationScheduling': 'Automatisierung & Planung',
    'settings.autoSave': 'Automatisch speichern',
    'settings.autoSaveHelp': 'Änderungen wenn möglich automatisch speichern',
    'settings.autoRunAnalysis': 'Analyse automatisch ausführen',
    'settings.autoRunAnalysisHelp': 'Periodische Lückenanalysen planen',
    'settings.scheduleFrequency': 'Ausführungsfrequenz',
    'settings.scheduleFrequencyHelp': 'Festlegen, wie oft Prüfungen laufen',
    'settings.userManagement': 'Benutzerverwaltung',
    'settings.activeUser': 'Aktiver Benutzer',
    'settings.inviteTeamMember': 'Teammitglied einladen',
  },
  fr: {
    dashboard: 'Tableau de Bord',
    understand: 'Comprendre Ma Situation',
    documents: 'Contrôles de Documents',
    risks: 'Gérer les Risques',
    evidence: 'Collecter des Preuves',
    findings: 'Gérer les Constatations',
    audit: 'Préparer l\'Audit',
    integrity: 'Intégrité de la Conformité',
    regfeed: 'Flux Réglementaire',
    settings: 'Paramètres',
    escalation: 'Règles d\'Escalade',
    integrations: 'Intégrations',
    gapAnalysis: 'Analyse des Écarts',
    documentGenerator: 'Générateur de Documents',
    riskMap: 'Carte des Risques',
    evidenceCenter: 'Centre de Preuves',
    capaTracker: 'Suivi CAPA',
    auditRoom: 'Salle d\'Audit',
    searchPlaceholder: 'Rechercher des contrôles ou des preuves...',
    administrator: 'Administrateur',
    chatPlaceholder: 'Tapez un message...',
    send: 'Envoyer',

    // Header
    'header.searchPlaceholder': 'Rechercher des contrôles ou des preuves...',
    'header.plan': 'Plan',
    'header.viewProfile': 'Voir le Profil',
    'header.settings': 'Paramètres',
    'header.signOut': 'Se Déconnecter',

    // Sidebar
    'sidebar.orgProfile': 'Profil d\'Organisation',
    'sidebar.change': 'Changer',
    'sidebar.byProcess': 'Par Processus',
    'sidebar.byModule': 'Par Module',
    'sidebar.complianceJourney': 'Parcours de Conformité',
    'sidebar.intelligence': 'Intelligence',
    'sidebar.coreModules': 'Modules Principaux',
    'sidebar.regulatoryModules': 'Modules Réglementaires',
    'sidebar.settings': 'Paramètres',
    'sidebar.availableInPlan': 'Disponible dans le Plan {plan}',

    // Menu Items
    'menu.dashboard': 'Tableau de Bord',
    'menu.understand': 'Comprendre',
    'menu.documents': 'Documents',
    'menu.risks': 'Risques',
    'menu.evidence': 'Preuves',
    'menu.findings': 'Constatations',
    'menu.audit': 'Audit',
    'menu.integrity': 'Intégrité',
    'menu.regfeed': 'Flux Réglementaire',
    'menu.gapAnalysis': 'Analyse des Écarts',
    'menu.documentGenerator': 'Générateur de Documents',
    'menu.riskMap': 'Carte des Risques',
    'menu.evidenceCenter': 'Centre de Preuves',
    'menu.capaTracker': 'Suivi CAPA',
    'menu.auditRoom': 'Salle d\'Audit',
    'menu.preAuditAssessment': 'Auto-évaluation Pré-audit',
    'menu.dora': 'DORA',
    'menu.euai': 'Loi UE sur l\'IA',
    'menu.escalation': 'Règles d\'Escalade',
    'menu.integrations': 'Intégrations',
    'menu.settings': 'Paramètres',
    'menu.assets': 'Inventaire des Actifs',

    profile: 'Profil',
    exportReport: 'Exporter le Rapport',
    addFramework: 'Ajouter un Framework',
    overallCompliance: 'Santé Globale de la Conformité',
    documentation: 'Documentation',
    implementation: 'Implémentation',
    tested: 'Testé / Efficace',
    'dashboard.documentation': 'Documentation',
    'dashboard.implementation': 'Implémentation',
    'dashboard.tested': 'Testé / Efficace',
    autoTracked: 'Auto-suivi',
    reviewNeeded: 'Révision nécessaire',
    humanRequired: 'Humain requis',
    fromLastMonth: 'du mois dernier',
    docsPending: 'docs en attente de révision',
    controlsUnverified: 'contrôles non vérifiés',
    controlsUntested: 'contrôles non testés',
    'dashboard.overview': 'Aperçu de la santé de conformité et des progrès',
    'dashboard.kpiLoadError': 'Impossible de charger les KPI',
    'dashboard.loadingKpis': 'Chargement des KPI...',
    'dashboard.healthScoreTrend': 'Tendance du score de santé',
    'dashboard.recentActivity': 'Activité récente',
    'dashboard.upcomingTasks': 'Tâches à venir',
    'kpi.noData': 'Aucune donnée disponible',
    'kpi.compliance': 'Conformité',
    'healthScore.subtitle': 'Préparation à la conformité calculée par le backend',
    'healthScore.readyLevel': 'Niveau de préparation',
    'healthScore.status.ready': 'Prêt',
    'healthScore.status.in_progress': 'En cours',
    'healthScore.status.at_risk': 'À risque',
    'healthScore.status.critical': 'Critique',
    'dashboard.activity.gapAnalysis': 'Analyse des écarts terminée pour ISO 27001',
    'dashboard.activity.evidence': 'Preuve téléchargée pour A.8.1',
    'dashboard.activity.capa': 'CAPA NC-2024-015 mise à jour',
    'dashboard.activity.risk': 'Plan de traitement du risque R-001 approuvé',
    'dashboard.time.2hours': 'il y a 2 heures',
    'dashboard.time.5hours': 'il y a 5 heures',
    'dashboard.time.1day': 'il y a 1 jour',
    'dashboard.time.2days': 'il y a 2 jours',
    'dashboard.task.evidence': 'Terminer la preuve pour A.9.2',
    'dashboard.task.capa': 'Examiner la CAPA NC-2025-002',
    'dashboard.task.risk': 'Mettre à jour le plan de traitement des risques',
    'dashboard.task.auditDocs': 'Préparer la documentation d’audit',
    'dashboard.due.today': 'Aujourd’hui',
    'dashboard.due.tomorrow': 'Demain',
    'dashboard.due.thisWeek': 'Cette semaine',
    'dashboard.due.nextWeek': 'La semaine prochaine',
    'dashboard.priority.high': 'ÉLEVÉ',
    'dashboard.priority.medium': 'MOYEN',
    'dashboard.priority.low': 'FAIBLE',
    'audit.title': 'Audit de Conformité',
    'audit.subtitle': 'Validez vos preuves selon les normes ISO 27001',
    'audit.fileValidatorTitle': 'Valider un fichier avec l’agent',
    'audit.dropHint': 'Cliquez ou faites glisser un fichier',
    'audit.dropSubHint': 'PDF, Word, Excel, texte, images (max 10 Mo)',
    'audit.processing': 'Validation granulaire en cours...',
    'audit.jobId': 'ID de tâche',
    'audit.progress': 'Progression',
    'audit.file': 'Fichier',
    'audit.avgCompliance': 'Conformité moyenne',
    'audit.status': 'Statut',
    'audit.validationCompleted': 'Validation terminée',
    'audit.summary': 'Résumé',
    'audit.findingsByChunk': 'Constats par section ISO',
    'audit.score': 'Score',
    'audit.relevance': 'Pertinence',
    'audit.suggestions': 'Suggestions',
    'audit.failed': 'La validation granulaire a échoué.',
    'audit.titleField': 'Titre de l’audit',
    'audit.descriptionField': 'Description',
    'audit.typeField': 'Type d’audit',
    'audit.priorityField': 'Priorité',
    'audit.evidenceField': 'Preuve',
    'audit.titlePlaceholder': 'Ex. : Évaluation de la sécurité physique',
    'audit.descriptionPlaceholder': 'Brève description de l’audit',
    'audit.evidencePlaceholder': 'Décrivez la preuve à analyser...',
    'audit.type.security': 'Sécurité',
    'audit.type.compliance': 'Conformité',
    'audit.type.operational': 'Opérationnel',
    'audit.type.financial': 'Financier',
    'audit.priority.low': 'Faible',
    'audit.priority.medium': 'Moyenne',
    'audit.priority.high': 'Élevée',
    'audit.priority.critical': 'Critique',
    'audit.validateButton': 'Valider l’audit',
    'audit.validatingButton': 'Validation en cours...',
    'audit.resultsTitle': 'Résultats de l’audit',
    'audit.checklistTitle': 'Checklist de pré-audit',
    'audit.checklistSubtitle': 'Persistance backend avec sauvegarde automatique',
    'audit.completed': 'terminé',
    'audit.saveNow': 'Enregistrer maintenant',
    'audit.checklistSaving': 'Enregistrement...',
    'audit.checklistDirty': 'Modifications en attente',
    'audit.savedAt': 'Enregistré',
    'audit.evidenceSeed': 'Nous avons 5 serveurs physiques dans la salle de réunion principale. Les serveurs sont sur la table de conférence et tout visiteur peut les voir.',
    'audit.checklist.pending': 'En attente',
    'audit.checklist.inProgress': 'En cours',
    'audit.checklist.done': 'Terminé',
    'audit.checklist.blocked': 'Bloqué',
    'audit.checklistNotesPlaceholder': 'Notes de preuve, observations ou blocages...',
    'audit.openChat': 'Ouvrir le chat',
    'audit.closeChat': 'Fermer le chat',
    'audit.chatPlaceholder': 'Posez une question à l’agent...',
    'audit.checklist.PRE-AUD-01': 'Définir le périmètre et les objectifs de l’audit',
    'audit.checklist.PRE-AUD-02': 'Collecter les preuves clés par contrôle',
    'audit.checklist.PRE-AUD-03': 'Confirmer les propriétaires et responsables',
    'audit.checklist.PRE-AUD-04': 'Examiner les constats ouverts et CAPA',
    'audit.checklist.PRE-AUD-05': 'Exécuter une simulation d’audit (dry run)',
    'audit.chatGreeting': 'Bonjour ! Je suis l’agent d’audit. Je suis prêt à analyser vos preuves de conformité et à fournir une validation basée sur les normes ISO 27001.',
    'audit.chatAnalysisComplete': 'J’ai terminé l’analyse d’audit. Score de conformité : {score} %. Statut : {status}. J’ai trouvé {count} constats.',
    'audit.chatRiskResponse': 'Les risques critiques identifiés incluent un accès physique non contrôlé aux équipements, l’absence de MFA et des politiques de rotation des identifiants insuffisantes.',
    'audit.chatRecommendationResponse': 'Recommandations : 1) Mettre en place un accès physique contrôlé, 2) Activer le MFA sur tous les systèmes, 3) Définir des politiques de rotation des identifiants tous les 90 jours.',
    'audit.chatFallback': 'Compris. Sur la base de l’analyse d’audit, je peux vous aider avec les constats, les recommandations ou les prochaines étapes.',
    'audit.unknownError': 'Erreur inconnue',
    'audit.fileValidationError': 'Erreur de validation du fichier',
    'audit.granularValidationStartError': 'Impossible de démarrer la validation granulaire',
    'audit.checklistLoadError': 'Impossible de charger la checklist',
    'audit.checklistSaveError': 'Impossible d’enregistrer la checklist',
    'audit.jobQueued': 'Tâche en file d’attente',
    'audit.validationError': 'Erreur de validation',
    'audit.validationUnknownError': 'Erreur de validation inconnue',
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Ajustez la langue, l’apparence, les notifications et l’automatisation.',
    'settings.organizationProfile': 'Profil de l’organisation',
    'settings.currentProfile': 'Profil actuel',
    'settings.profile.foundational': 'Fondamental',
    'settings.profile.established': 'Établi',
    'settings.profile.advanced': 'Avancé',
    'settings.profile.mature': 'Mûr',
    'settings.profileDesc.foundational': 'Mode guidé avec plus d’aide et d’explications',
    'settings.profileDesc.established': 'Mode équilibré avec navigation par processus et modules',
    'settings.profileDesc.advanced': 'Mode centré sur les modules avec moins de guidance',
    'settings.profileDesc.mature': 'Mode très autonome pour équipes avancées',
    'settings.languageRegion': 'Langue & Région',
    'settings.interfaceLanguage': "Langue de l’interface",
    'settings.controlsUI': 'Contrôle la langue de toute la plateforme',
    'settings.dateFormat': 'Format de date',
    'settings.dateFormatHelp': 'Comment les dates sont affichées dans l’interface',
    'settings.timezone': 'Fuseau horaire',
    'settings.timezoneHelp': 'Utilisé pour les rappels et les horodatages',
    'settings.appearance': 'Apparence',
    'settings.darkMode': 'Mode sombre',
    'settings.darkModeHelp': 'Basculer entre le thème clair et sombre',
    'settings.compactView': 'Vue compacte',
    'settings.compactViewHelp': 'Réduire l’espace dans les tableaux et cartes',
    'settings.sidebarLabels': 'Afficher les libellés de la barre latérale',
    'settings.sidebarLabelsHelp': 'Afficher le texte dans la navigation',
    'settings.notifications': 'Notifications',
    'settings.emailNotifications': 'Notifications par e-mail',
    'settings.emailNotificationsHelp': 'Recevoir les alertes de conformité par e-mail',
    'settings.capaReminders': 'Rappels CAPA',
    'settings.capaRemindersHelp': 'Rappeler les actions correctives en retard',
    'settings.regulatoryUpdates': 'Mises à jour réglementaires',
    'settings.regulatoryUpdatesHelp': 'Avertir des nouveaux changements réglementaires',
    'settings.auditDeadlines': 'Délais d’audit',
    'settings.auditDeadlinesHelp': 'Notifier avant les dates clés d’audit',
    'settings.automationScheduling': 'Automatisation & Planification',
    'settings.autoSave': 'Sauvegarde automatique',
    'settings.autoSaveHelp': 'Enregistrer automatiquement quand c’est possible',
    'settings.autoRunAnalysis': 'Analyse automatique',
    'settings.autoRunAnalysisHelp': 'Planifier des analyses d’écart périodiques',
    'settings.scheduleFrequency': 'Fréquence de planification',
    'settings.scheduleFrequencyHelp': 'Choisissez la fréquence des vérifications automatiques',
    'settings.userManagement': 'Gestion des utilisateurs',
    'settings.activeUser': 'Utilisateur actif',
    'settings.inviteTeamMember': 'Inviter un membre de l’équipe',
  },
};
