"""add assets

Revision ID: af8da8d134ad
Revises: cdc63d67aa41
Create Date: 2026-04-27 17:53:35.476050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8da8d134ad'
down_revision: Union[str, Sequence[str], None] = 'cdc63d67aa41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidentiality', sa.Integer(), nullable=False),
    sa.Column('integrity', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Integer(), nullable=False),
    sa.Column('criticality_score', sa.Float(), nullable=False),
    sa.Column('criticality_level', sa.String(length=20), nullable=False),
    sa.Column('clause_ref', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_organization_id'), 'assets', ['organization_id'], unique=False)
    #op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    #op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_assets_organization_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
